//! Register file definition for rv64gc.
//!
//! This file was generated by `gen_reg_file.py`

#![allow(non_camel_case_types)]

use crate::{Register, RegState};
#[allow(unused_imports)]
use val::{Big, ILVal};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum rv64gcReg {
	a0,
	a1,
	a2,
	a3,
	a4,
	a5,
	a6,
	a7,
	fa0,
	fa1,
	fa2,
	fa3,
	fa4,
	fa5,
	fa6,
	fa7,
	fs0,
	fs1,
	fs10,
	fs11,
	fs2,
	fs3,
	fs4,
	fs5,
	fs6,
	fs7,
	fs8,
	fs9,
	ft0,
	ft1,
	ft10,
	ft11,
	ft2,
	ft3,
	ft4,
	ft5,
	ft6,
	ft7,
	ft8,
	ft9,
	gp,
	ra,
	s0,
	s1,
	s10,
	s11,
	s2,
	s3,
	s4,
	s5,
	s6,
	s7,
	s8,
	s9,
	sp,
	t0,
	t1,
	t2,
	t3,
	t4,
	t5,
	t6,
	tp,
	zero,
}

impl TryFrom<u32> for rv64gcReg {
	type Error = u32;

	fn try_from(reg_id: u32) -> Result<Self, u32> {
		match reg_id {
			0 => Ok(Self::zero),
			1 => Ok(Self::ra),
			2 => Ok(Self::sp),
			3 => Ok(Self::gp),
			4 => Ok(Self::tp),
			5 => Ok(Self::t0),
			6 => Ok(Self::t1),
			7 => Ok(Self::t2),
			8 => Ok(Self::s0),
			9 => Ok(Self::s1),
			10 => Ok(Self::a0),
			11 => Ok(Self::a1),
			12 => Ok(Self::a2),
			13 => Ok(Self::a3),
			14 => Ok(Self::a4),
			15 => Ok(Self::a5),
			16 => Ok(Self::a6),
			17 => Ok(Self::a7),
			18 => Ok(Self::s2),
			19 => Ok(Self::s3),
			20 => Ok(Self::s4),
			21 => Ok(Self::s5),
			22 => Ok(Self::s6),
			23 => Ok(Self::s7),
			24 => Ok(Self::s8),
			25 => Ok(Self::s9),
			26 => Ok(Self::s10),
			27 => Ok(Self::s11),
			28 => Ok(Self::t3),
			29 => Ok(Self::t4),
			30 => Ok(Self::t5),
			31 => Ok(Self::t6),
			32 => Ok(Self::ft0),
			33 => Ok(Self::ft1),
			34 => Ok(Self::ft2),
			35 => Ok(Self::ft3),
			36 => Ok(Self::ft4),
			37 => Ok(Self::ft5),
			38 => Ok(Self::ft6),
			39 => Ok(Self::ft7),
			40 => Ok(Self::fs0),
			41 => Ok(Self::fs1),
			42 => Ok(Self::fa0),
			43 => Ok(Self::fa1),
			44 => Ok(Self::fa2),
			45 => Ok(Self::fa3),
			46 => Ok(Self::fa4),
			47 => Ok(Self::fa5),
			48 => Ok(Self::fa6),
			49 => Ok(Self::fa7),
			50 => Ok(Self::fs2),
			51 => Ok(Self::fs3),
			52 => Ok(Self::fs4),
			53 => Ok(Self::fs5),
			54 => Ok(Self::fs6),
			55 => Ok(Self::fs7),
			56 => Ok(Self::fs8),
			57 => Ok(Self::fs9),
			58 => Ok(Self::fs10),
			59 => Ok(Self::fs11),
			60 => Ok(Self::ft8),
			61 => Ok(Self::ft9),
			62 => Ok(Self::ft10),
			63 => Ok(Self::ft11),
			_ => Err(reg_id),
		}
	}
}

impl std::fmt::Display for rv64gcReg {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		write!(f, "{:?}", self)
	}
}

impl Register for rv64gcReg {
	fn size(&self) -> u8 {
		match self {
			Self::zero => 8,
			Self::ra => 8,
			Self::sp => 8,
			Self::gp => 8,
			Self::tp => 8,
			Self::t0 => 8,
			Self::t1 => 8,
			Self::t2 => 8,
			Self::s0 => 8,
			Self::s1 => 8,
			Self::a0 => 8,
			Self::a1 => 8,
			Self::a2 => 8,
			Self::a3 => 8,
			Self::a4 => 8,
			Self::a5 => 8,
			Self::a6 => 8,
			Self::a7 => 8,
			Self::s2 => 8,
			Self::s3 => 8,
			Self::s4 => 8,
			Self::s5 => 8,
			Self::s6 => 8,
			Self::s7 => 8,
			Self::s8 => 8,
			Self::s9 => 8,
			Self::s10 => 8,
			Self::s11 => 8,
			Self::t3 => 8,
			Self::t4 => 8,
			Self::t5 => 8,
			Self::t6 => 8,
			Self::ft0 => 8,
			Self::ft1 => 8,
			Self::ft2 => 8,
			Self::ft3 => 8,
			Self::ft4 => 8,
			Self::ft5 => 8,
			Self::ft6 => 8,
			Self::ft7 => 8,
			Self::fs0 => 8,
			Self::fs1 => 8,
			Self::fa0 => 8,
			Self::fa1 => 8,
			Self::fa2 => 8,
			Self::fa3 => 8,
			Self::fa4 => 8,
			Self::fa5 => 8,
			Self::fa6 => 8,
			Self::fa7 => 8,
			Self::fs2 => 8,
			Self::fs3 => 8,
			Self::fs4 => 8,
			Self::fs5 => 8,
			Self::fs6 => 8,
			Self::fs7 => 8,
			Self::fs8 => 8,
			Self::fs9 => 8,
			Self::fs10 => 8,
			Self::fs11 => 8,
			Self::ft8 => 8,
			Self::ft9 => 8,
			Self::ft10 => 8,
			Self::ft11 => 8,
		}
	}
}

#[derive(Clone, Copy, Debug, Default)]
pub struct rv64gcRegFile {
	pub a0: u64,
	pub a1: u64,
	pub a2: u64,
	pub a3: u64,
	pub a4: u64,
	pub a5: u64,
	pub a6: u64,
	pub a7: u64,
	pub fa0: u64,
	pub fa1: u64,
	pub fa2: u64,
	pub fa3: u64,
	pub fa4: u64,
	pub fa5: u64,
	pub fa6: u64,
	pub fa7: u64,
	pub fs0: u64,
	pub fs1: u64,
	pub fs10: u64,
	pub fs11: u64,
	pub fs2: u64,
	pub fs3: u64,
	pub fs4: u64,
	pub fs5: u64,
	pub fs6: u64,
	pub fs7: u64,
	pub fs8: u64,
	pub fs9: u64,
	pub ft0: u64,
	pub ft1: u64,
	pub ft10: u64,
	pub ft11: u64,
	pub ft2: u64,
	pub ft3: u64,
	pub ft4: u64,
	pub ft5: u64,
	pub ft6: u64,
	pub ft7: u64,
	pub ft8: u64,
	pub ft9: u64,
	pub gp: u64,
	pub ra: u64,
	pub s0: u64,
	pub s1: u64,
	pub s10: u64,
	pub s11: u64,
	pub s2: u64,
	pub s3: u64,
	pub s4: u64,
	pub s5: u64,
	pub s6: u64,
	pub s7: u64,
	pub s8: u64,
	pub s9: u64,
	pub sp: u64,
	pub t0: u64,
	pub t1: u64,
	pub t2: u64,
	pub t3: u64,
	pub t4: u64,
	pub t5: u64,
	pub t6: u64,
	pub tp: u64,
	pub zero: u64,
}

impl RegState for rv64gcRegFile {
	type RegID = rv64gcReg;

	fn read(&self, id: Self::RegID) -> ILVal {
		match id {
			rv64gcReg::zero => {
				ILVal::Quad(self.zero)
			}
			rv64gcReg::ra => {
				ILVal::Quad(self.ra)
			}
			rv64gcReg::sp => {
				ILVal::Quad(self.sp)
			}
			rv64gcReg::gp => {
				ILVal::Quad(self.gp)
			}
			rv64gcReg::tp => {
				ILVal::Quad(self.tp)
			}
			rv64gcReg::t0 => {
				ILVal::Quad(self.t0)
			}
			rv64gcReg::t1 => {
				ILVal::Quad(self.t1)
			}
			rv64gcReg::t2 => {
				ILVal::Quad(self.t2)
			}
			rv64gcReg::s0 => {
				ILVal::Quad(self.s0)
			}
			rv64gcReg::s1 => {
				ILVal::Quad(self.s1)
			}
			rv64gcReg::a0 => {
				ILVal::Quad(self.a0)
			}
			rv64gcReg::a1 => {
				ILVal::Quad(self.a1)
			}
			rv64gcReg::a2 => {
				ILVal::Quad(self.a2)
			}
			rv64gcReg::a3 => {
				ILVal::Quad(self.a3)
			}
			rv64gcReg::a4 => {
				ILVal::Quad(self.a4)
			}
			rv64gcReg::a5 => {
				ILVal::Quad(self.a5)
			}
			rv64gcReg::a6 => {
				ILVal::Quad(self.a6)
			}
			rv64gcReg::a7 => {
				ILVal::Quad(self.a7)
			}
			rv64gcReg::s2 => {
				ILVal::Quad(self.s2)
			}
			rv64gcReg::s3 => {
				ILVal::Quad(self.s3)
			}
			rv64gcReg::s4 => {
				ILVal::Quad(self.s4)
			}
			rv64gcReg::s5 => {
				ILVal::Quad(self.s5)
			}
			rv64gcReg::s6 => {
				ILVal::Quad(self.s6)
			}
			rv64gcReg::s7 => {
				ILVal::Quad(self.s7)
			}
			rv64gcReg::s8 => {
				ILVal::Quad(self.s8)
			}
			rv64gcReg::s9 => {
				ILVal::Quad(self.s9)
			}
			rv64gcReg::s10 => {
				ILVal::Quad(self.s10)
			}
			rv64gcReg::s11 => {
				ILVal::Quad(self.s11)
			}
			rv64gcReg::t3 => {
				ILVal::Quad(self.t3)
			}
			rv64gcReg::t4 => {
				ILVal::Quad(self.t4)
			}
			rv64gcReg::t5 => {
				ILVal::Quad(self.t5)
			}
			rv64gcReg::t6 => {
				ILVal::Quad(self.t6)
			}
			rv64gcReg::ft0 => {
				ILVal::Quad(self.ft0)
			}
			rv64gcReg::ft1 => {
				ILVal::Quad(self.ft1)
			}
			rv64gcReg::ft2 => {
				ILVal::Quad(self.ft2)
			}
			rv64gcReg::ft3 => {
				ILVal::Quad(self.ft3)
			}
			rv64gcReg::ft4 => {
				ILVal::Quad(self.ft4)
			}
			rv64gcReg::ft5 => {
				ILVal::Quad(self.ft5)
			}
			rv64gcReg::ft6 => {
				ILVal::Quad(self.ft6)
			}
			rv64gcReg::ft7 => {
				ILVal::Quad(self.ft7)
			}
			rv64gcReg::fs0 => {
				ILVal::Quad(self.fs0)
			}
			rv64gcReg::fs1 => {
				ILVal::Quad(self.fs1)
			}
			rv64gcReg::fa0 => {
				ILVal::Quad(self.fa0)
			}
			rv64gcReg::fa1 => {
				ILVal::Quad(self.fa1)
			}
			rv64gcReg::fa2 => {
				ILVal::Quad(self.fa2)
			}
			rv64gcReg::fa3 => {
				ILVal::Quad(self.fa3)
			}
			rv64gcReg::fa4 => {
				ILVal::Quad(self.fa4)
			}
			rv64gcReg::fa5 => {
				ILVal::Quad(self.fa5)
			}
			rv64gcReg::fa6 => {
				ILVal::Quad(self.fa6)
			}
			rv64gcReg::fa7 => {
				ILVal::Quad(self.fa7)
			}
			rv64gcReg::fs2 => {
				ILVal::Quad(self.fs2)
			}
			rv64gcReg::fs3 => {
				ILVal::Quad(self.fs3)
			}
			rv64gcReg::fs4 => {
				ILVal::Quad(self.fs4)
			}
			rv64gcReg::fs5 => {
				ILVal::Quad(self.fs5)
			}
			rv64gcReg::fs6 => {
				ILVal::Quad(self.fs6)
			}
			rv64gcReg::fs7 => {
				ILVal::Quad(self.fs7)
			}
			rv64gcReg::fs8 => {
				ILVal::Quad(self.fs8)
			}
			rv64gcReg::fs9 => {
				ILVal::Quad(self.fs9)
			}
			rv64gcReg::fs10 => {
				ILVal::Quad(self.fs10)
			}
			rv64gcReg::fs11 => {
				ILVal::Quad(self.fs11)
			}
			rv64gcReg::ft8 => {
				ILVal::Quad(self.ft8)
			}
			rv64gcReg::ft9 => {
				ILVal::Quad(self.ft9)
			}
			rv64gcReg::ft10 => {
				ILVal::Quad(self.ft10)
			}
			rv64gcReg::ft11 => {
				ILVal::Quad(self.ft11)
			}
		}
	}

	fn write(&mut self, id: Self::RegID, val: &ILVal) {
		match id {
			rv64gcReg::zero => {
				self.zero = val.get_quad();
			}
			rv64gcReg::ra => {
				self.ra = val.get_quad();
			}
			rv64gcReg::sp => {
				self.sp = val.get_quad();
			}
			rv64gcReg::gp => {
				self.gp = val.get_quad();
			}
			rv64gcReg::tp => {
				self.tp = val.get_quad();
			}
			rv64gcReg::t0 => {
				self.t0 = val.get_quad();
			}
			rv64gcReg::t1 => {
				self.t1 = val.get_quad();
			}
			rv64gcReg::t2 => {
				self.t2 = val.get_quad();
			}
			rv64gcReg::s0 => {
				self.s0 = val.get_quad();
			}
			rv64gcReg::s1 => {
				self.s1 = val.get_quad();
			}
			rv64gcReg::a0 => {
				self.a0 = val.get_quad();
			}
			rv64gcReg::a1 => {
				self.a1 = val.get_quad();
			}
			rv64gcReg::a2 => {
				self.a2 = val.get_quad();
			}
			rv64gcReg::a3 => {
				self.a3 = val.get_quad();
			}
			rv64gcReg::a4 => {
				self.a4 = val.get_quad();
			}
			rv64gcReg::a5 => {
				self.a5 = val.get_quad();
			}
			rv64gcReg::a6 => {
				self.a6 = val.get_quad();
			}
			rv64gcReg::a7 => {
				self.a7 = val.get_quad();
			}
			rv64gcReg::s2 => {
				self.s2 = val.get_quad();
			}
			rv64gcReg::s3 => {
				self.s3 = val.get_quad();
			}
			rv64gcReg::s4 => {
				self.s4 = val.get_quad();
			}
			rv64gcReg::s5 => {
				self.s5 = val.get_quad();
			}
			rv64gcReg::s6 => {
				self.s6 = val.get_quad();
			}
			rv64gcReg::s7 => {
				self.s7 = val.get_quad();
			}
			rv64gcReg::s8 => {
				self.s8 = val.get_quad();
			}
			rv64gcReg::s9 => {
				self.s9 = val.get_quad();
			}
			rv64gcReg::s10 => {
				self.s10 = val.get_quad();
			}
			rv64gcReg::s11 => {
				self.s11 = val.get_quad();
			}
			rv64gcReg::t3 => {
				self.t3 = val.get_quad();
			}
			rv64gcReg::t4 => {
				self.t4 = val.get_quad();
			}
			rv64gcReg::t5 => {
				self.t5 = val.get_quad();
			}
			rv64gcReg::t6 => {
				self.t6 = val.get_quad();
			}
			rv64gcReg::ft0 => {
				self.ft0 = val.get_quad();
			}
			rv64gcReg::ft1 => {
				self.ft1 = val.get_quad();
			}
			rv64gcReg::ft2 => {
				self.ft2 = val.get_quad();
			}
			rv64gcReg::ft3 => {
				self.ft3 = val.get_quad();
			}
			rv64gcReg::ft4 => {
				self.ft4 = val.get_quad();
			}
			rv64gcReg::ft5 => {
				self.ft5 = val.get_quad();
			}
			rv64gcReg::ft6 => {
				self.ft6 = val.get_quad();
			}
			rv64gcReg::ft7 => {
				self.ft7 = val.get_quad();
			}
			rv64gcReg::fs0 => {
				self.fs0 = val.get_quad();
			}
			rv64gcReg::fs1 => {
				self.fs1 = val.get_quad();
			}
			rv64gcReg::fa0 => {
				self.fa0 = val.get_quad();
			}
			rv64gcReg::fa1 => {
				self.fa1 = val.get_quad();
			}
			rv64gcReg::fa2 => {
				self.fa2 = val.get_quad();
			}
			rv64gcReg::fa3 => {
				self.fa3 = val.get_quad();
			}
			rv64gcReg::fa4 => {
				self.fa4 = val.get_quad();
			}
			rv64gcReg::fa5 => {
				self.fa5 = val.get_quad();
			}
			rv64gcReg::fa6 => {
				self.fa6 = val.get_quad();
			}
			rv64gcReg::fa7 => {
				self.fa7 = val.get_quad();
			}
			rv64gcReg::fs2 => {
				self.fs2 = val.get_quad();
			}
			rv64gcReg::fs3 => {
				self.fs3 = val.get_quad();
			}
			rv64gcReg::fs4 => {
				self.fs4 = val.get_quad();
			}
			rv64gcReg::fs5 => {
				self.fs5 = val.get_quad();
			}
			rv64gcReg::fs6 => {
				self.fs6 = val.get_quad();
			}
			rv64gcReg::fs7 => {
				self.fs7 = val.get_quad();
			}
			rv64gcReg::fs8 => {
				self.fs8 = val.get_quad();
			}
			rv64gcReg::fs9 => {
				self.fs9 = val.get_quad();
			}
			rv64gcReg::fs10 => {
				self.fs10 = val.get_quad();
			}
			rv64gcReg::fs11 => {
				self.fs11 = val.get_quad();
			}
			rv64gcReg::ft8 => {
				self.ft8 = val.get_quad();
			}
			rv64gcReg::ft9 => {
				self.ft9 = val.get_quad();
			}
			rv64gcReg::ft10 => {
				self.ft10 = val.get_quad();
			}
			rv64gcReg::ft11 => {
				self.ft11 = val.get_quad();
			}
		}
	}
}

