//! Register file definition for x86.
//!
//! This file was generated by `gen_reg_file.py`

#![allow(non_camel_case_types)]

use crate::{Register, RegState};
#[allow(unused_imports)]
use val::{Big, ILVal};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum x86Reg {
	ah,
	al,
	ax,
	bh,
	bl,
	bnd0,
	bnd1,
	bnd2,
	bnd3,
	bp,
	bx,
	ch,
	cl,
	cr0,
	cr1,
	cr10,
	cr11,
	cr12,
	cr13,
	cr14,
	cr15,
	cr2,
	cr3,
	cr4,
	cr5,
	cr6,
	cr7,
	cr8,
	cr9,
	cs,
	cx,
	dh,
	di,
	dl,
	dr0,
	dr1,
	dr2,
	dr3,
	dr4,
	dr5,
	dr6,
	dr7,
	ds,
	dx,
	eax,
	ebp,
	ebx,
	ecx,
	edi,
	edx,
	eflags,
	eip,
	es,
	esi,
	esp,
	flags,
	fs,
	fsbase,
	gdtr,
	gs,
	gsbase,
	idtr,
	ip,
	ldtr,
	mm0,
	mm1,
	mm2,
	mm3,
	mm4,
	mm5,
	mm6,
	mm7,
	msrs,
	mxcsr,
	rflags,
	si,
	sp,
	ss,
	st0,
	st1,
	st2,
	st3,
	st4,
	st5,
	st6,
	st7,
	top,
	tr,
	tsc,
	tscaux,
	x87_r0,
	x87_r1,
	x87_r2,
	x87_r3,
	x87_r4,
	x87_r5,
	x87_r6,
	x87_r7,
	x87control,
	x87lastcs,
	x87lastdp,
	x87lastds,
	x87lastip,
	x87opcode,
	x87pop,
	x87pop2,
	x87push,
	x87status,
	x87tag,
	xcr0,
	xmm0,
	xmm1,
	xmm2,
	xmm3,
	xmm4,
	xmm5,
	xmm6,
	xmm7,
}

impl TryFrom<u32> for x86Reg {
	type Error = u32;

	fn try_from(reg_id: u32) -> Result<Self, u32> {
		match reg_id {
			162 => Ok(Self::ah),
			163 => Ok(Self::ch),
			164 => Ok(Self::dh),
			165 => Ok(Self::bh),
			130 => Ok(Self::al),
			131 => Ok(Self::cl),
			132 => Ok(Self::dl),
			133 => Ok(Self::bl),
			169 => Ok(Self::ip),
			230 => Ok(Self::cs),
			232 => Ok(Self::ds),
			229 => Ok(Self::es),
			231 => Ok(Self::ss),
			233 => Ok(Self::fs),
			234 => Ok(Self::gs),
			198 => Ok(Self::fsbase),
			199 => Ok(Self::gsbase),
			38 => Ok(Self::sp),
			39 => Ok(Self::bp),
			40 => Ok(Self::si),
			41 => Ok(Self::di),
			31 => Ok(Self::flags),
			34 => Ok(Self::ax),
			35 => Ok(Self::cx),
			36 => Ok(Self::dx),
			37 => Ok(Self::bx),
			4104 => Ok(Self::top),
			218 => Ok(Self::x87control),
			219 => Ok(Self::x87status),
			220 => Ok(Self::x87tag),
			221 => Ok(Self::x87push),
			222 => Ok(Self::x87pop),
			223 => Ok(Self::x87pop2),
			224 => Ok(Self::x87opcode),
			225 => Ok(Self::x87lastcs),
			226 => Ok(Self::x87lastip),
			227 => Ok(Self::x87lastds),
			228 => Ok(Self::x87lastdp),
			168 => Ok(Self::eip),
			70 => Ok(Self::esp),
			71 => Ok(Self::ebp),
			72 => Ok(Self::esi),
			73 => Ok(Self::edi),
			32 => Ok(Self::eflags),
			66 => Ok(Self::eax),
			67 => Ok(Self::ecx),
			68 => Ok(Self::edx),
			69 => Ok(Self::ebx),
			195 => Ok(Self::tsc),
			196 => Ok(Self::tscaux),
			194 => Ok(Self::tr),
			7 => Ok(Self::cr0),
			8 => Ok(Self::cr1),
			9 => Ok(Self::cr2),
			10 => Ok(Self::cr3),
			11 => Ok(Self::cr4),
			12 => Ok(Self::cr5),
			13 => Ok(Self::cr6),
			14 => Ok(Self::cr7),
			15 => Ok(Self::cr8),
			16 => Ok(Self::cr9),
			17 => Ok(Self::cr10),
			18 => Ok(Self::cr11),
			19 => Ok(Self::cr12),
			20 => Ok(Self::cr13),
			21 => Ok(Self::cr14),
			22 => Ok(Self::cr15),
			23 => Ok(Self::dr0),
			24 => Ok(Self::dr1),
			25 => Ok(Self::dr2),
			26 => Ok(Self::dr3),
			27 => Ok(Self::dr4),
			28 => Ok(Self::dr5),
			29 => Ok(Self::dr6),
			30 => Ok(Self::dr7),
			188 => Ok(Self::mxcsr),
			191 => Ok(Self::gdtr),
			192 => Ok(Self::ldtr),
			193 => Ok(Self::idtr),
			178 => Ok(Self::mm0),
			179 => Ok(Self::mm1),
			180 => Ok(Self::mm2),
			181 => Ok(Self::mm3),
			182 => Ok(Self::mm4),
			183 => Ok(Self::mm5),
			184 => Ok(Self::mm6),
			185 => Ok(Self::mm7),
			268 => Ok(Self::xcr0),
			33 => Ok(Self::rflags),
			197 => Ok(Self::msrs),
			260 => Ok(Self::st0),
			261 => Ok(Self::st1),
			262 => Ok(Self::st2),
			263 => Ok(Self::st3),
			264 => Ok(Self::st4),
			265 => Ok(Self::st5),
			266 => Ok(Self::st6),
			267 => Ok(Self::st7),
			4096 => Ok(Self::x87_r0),
			4097 => Ok(Self::x87_r1),
			4098 => Ok(Self::x87_r2),
			4099 => Ok(Self::x87_r3),
			4100 => Ok(Self::x87_r4),
			4101 => Ok(Self::x87_r5),
			4102 => Ok(Self::x87_r6),
			4103 => Ok(Self::x87_r7),
			269 => Ok(Self::xmm0),
			270 => Ok(Self::xmm1),
			271 => Ok(Self::xmm2),
			272 => Ok(Self::xmm3),
			273 => Ok(Self::xmm4),
			274 => Ok(Self::xmm5),
			275 => Ok(Self::xmm6),
			276 => Ok(Self::xmm7),
			3 => Ok(Self::bnd0),
			4 => Ok(Self::bnd1),
			5 => Ok(Self::bnd2),
			6 => Ok(Self::bnd3),
			_ => Err(reg_id),
		}
	}
}

impl std::fmt::Display for x86Reg {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		write!(f, "{:?}", self)
	}
}

impl Register for x86Reg {
	fn size(&self) -> u8 {
		match self {
			Self::ah => 1,
			Self::ch => 1,
			Self::dh => 1,
			Self::bh => 1,
			Self::al => 1,
			Self::cl => 1,
			Self::dl => 1,
			Self::bl => 1,
			Self::ip => 2,
			Self::cs => 2,
			Self::ds => 2,
			Self::es => 2,
			Self::ss => 2,
			Self::fs => 2,
			Self::gs => 2,
			Self::fsbase => 4,
			Self::gsbase => 4,
			Self::sp => 2,
			Self::bp => 2,
			Self::si => 2,
			Self::di => 2,
			Self::flags => 2,
			Self::ax => 2,
			Self::cx => 2,
			Self::dx => 2,
			Self::bx => 2,
			Self::top => 2,
			Self::x87control => 2,
			Self::x87status => 2,
			Self::x87tag => 2,
			Self::x87push => 4,
			Self::x87pop => 4,
			Self::x87pop2 => 4,
			Self::x87opcode => 2,
			Self::x87lastcs => 2,
			Self::x87lastip => 4,
			Self::x87lastds => 2,
			Self::x87lastdp => 4,
			Self::eip => 4,
			Self::esp => 4,
			Self::ebp => 4,
			Self::esi => 4,
			Self::edi => 4,
			Self::eflags => 4,
			Self::eax => 4,
			Self::ecx => 4,
			Self::edx => 4,
			Self::ebx => 4,
			Self::tsc => 4,
			Self::tscaux => 4,
			Self::tr => 4,
			Self::cr0 => 4,
			Self::cr1 => 4,
			Self::cr2 => 4,
			Self::cr3 => 4,
			Self::cr4 => 4,
			Self::cr5 => 4,
			Self::cr6 => 4,
			Self::cr7 => 4,
			Self::cr8 => 4,
			Self::cr9 => 4,
			Self::cr10 => 4,
			Self::cr11 => 4,
			Self::cr12 => 4,
			Self::cr13 => 4,
			Self::cr14 => 4,
			Self::cr15 => 4,
			Self::dr0 => 4,
			Self::dr1 => 4,
			Self::dr2 => 4,
			Self::dr3 => 4,
			Self::dr4 => 4,
			Self::dr5 => 4,
			Self::dr6 => 4,
			Self::dr7 => 4,
			Self::mxcsr => 4,
			Self::gdtr => 6,
			Self::ldtr => 6,
			Self::idtr => 6,
			Self::mm0 => 8,
			Self::mm1 => 8,
			Self::mm2 => 8,
			Self::mm3 => 8,
			Self::mm4 => 8,
			Self::mm5 => 8,
			Self::mm6 => 8,
			Self::mm7 => 8,
			Self::xcr0 => 8,
			Self::rflags => 8,
			Self::msrs => 8,
			Self::st0 => 10,
			Self::st1 => 10,
			Self::st2 => 10,
			Self::st3 => 10,
			Self::st4 => 10,
			Self::st5 => 10,
			Self::st6 => 10,
			Self::st7 => 10,
			Self::x87_r0 => 10,
			Self::x87_r1 => 10,
			Self::x87_r2 => 10,
			Self::x87_r3 => 10,
			Self::x87_r4 => 10,
			Self::x87_r5 => 10,
			Self::x87_r6 => 10,
			Self::x87_r7 => 10,
			Self::xmm0 => 16,
			Self::xmm1 => 16,
			Self::xmm2 => 16,
			Self::xmm3 => 16,
			Self::xmm4 => 16,
			Self::xmm5 => 16,
			Self::xmm6 => 16,
			Self::xmm7 => 16,
			Self::bnd0 => 16,
			Self::bnd1 => 16,
			Self::bnd2 => 16,
			Self::bnd3 => 16,
		}
	}
}

#[derive(Clone, Copy, Debug, Default)]
pub struct x86RegFile {
	pub bnd0: [u8; 16],
	pub bnd1: [u8; 16],
	pub bnd2: [u8; 16],
	pub bnd3: [u8; 16],
	pub cr0: u32,
	pub cr1: u32,
	pub cr10: u32,
	pub cr11: u32,
	pub cr12: u32,
	pub cr13: u32,
	pub cr14: u32,
	pub cr15: u32,
	pub cr2: u32,
	pub cr3: u32,
	pub cr4: u32,
	pub cr5: u32,
	pub cr6: u32,
	pub cr7: u32,
	pub cr8: u32,
	pub cr9: u32,
	pub cs: u16,
	pub dr0: u32,
	pub dr1: u32,
	pub dr2: u32,
	pub dr3: u32,
	pub dr4: u32,
	pub dr5: u32,
	pub dr6: u32,
	pub dr7: u32,
	pub ds: u16,
	pub eax: u32,
	pub ebp: u32,
	pub ebx: u32,
	pub ecx: u32,
	pub edi: u32,
	pub edx: u32,
	pub eflags: u32,
	pub eip: u32,
	pub es: u16,
	pub esi: u32,
	pub esp: u32,
	pub fs: u16,
	pub fsbase: u32,
	pub gdtr: [u8; 6],
	pub gs: u16,
	pub gsbase: u32,
	pub idtr: [u8; 6],
	pub ldtr: [u8; 6],
	pub msrs: u64,
	pub mxcsr: u32,
	pub rflags: u64,
	pub ss: u16,
	pub st0: [u8; 10],
	pub st1: [u8; 10],
	pub st2: [u8; 10],
	pub st3: [u8; 10],
	pub st4: [u8; 10],
	pub st5: [u8; 10],
	pub st6: [u8; 10],
	pub st7: [u8; 10],
	pub top: u16,
	pub tr: u32,
	pub tsc: u32,
	pub tscaux: u32,
	pub x87_r0: [u8; 10],
	pub x87_r1: [u8; 10],
	pub x87_r2: [u8; 10],
	pub x87_r3: [u8; 10],
	pub x87_r4: [u8; 10],
	pub x87_r5: [u8; 10],
	pub x87_r6: [u8; 10],
	pub x87_r7: [u8; 10],
	pub x87control: u16,
	pub x87lastcs: u16,
	pub x87lastdp: u32,
	pub x87lastds: u16,
	pub x87lastip: u32,
	pub x87opcode: u16,
	pub x87pop: u32,
	pub x87pop2: u32,
	pub x87push: u32,
	pub x87status: u16,
	pub x87tag: u16,
	pub xcr0: u64,
	pub xmm0: [u8; 16],
	pub xmm1: [u8; 16],
	pub xmm2: [u8; 16],
	pub xmm3: [u8; 16],
	pub xmm4: [u8; 16],
	pub xmm5: [u8; 16],
	pub xmm6: [u8; 16],
	pub xmm7: [u8; 16],
}

impl RegState for x86RegFile {
	type RegID = x86Reg;

	fn read(&self, id: Self::RegID) -> ILVal {
		match id {
			x86Reg::ah => {
				let val = self.eax;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86Reg::ch => {
				let val = self.ecx;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86Reg::dh => {
				let val = self.edx;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86Reg::bh => {
				let val = self.ebx;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86Reg::al => {
				let val = self.eax;
				ILVal::Byte(val as u8)
			}
			x86Reg::cl => {
				let val = self.ecx;
				ILVal::Byte(val as u8)
			}
			x86Reg::dl => {
				let val = self.edx;
				ILVal::Byte(val as u8)
			}
			x86Reg::bl => {
				let val = self.ebx;
				ILVal::Byte(val as u8)
			}
			x86Reg::ip => {
				let val = self.eip;
				ILVal::Short(val as u16)
			}
			x86Reg::cs => {
				ILVal::Short(self.cs)
			}
			x86Reg::ds => {
				ILVal::Short(self.ds)
			}
			x86Reg::es => {
				ILVal::Short(self.es)
			}
			x86Reg::ss => {
				ILVal::Short(self.ss)
			}
			x86Reg::fs => {
				ILVal::Short(self.fs)
			}
			x86Reg::gs => {
				ILVal::Short(self.gs)
			}
			x86Reg::fsbase => {
				ILVal::Word(self.fsbase)
			}
			x86Reg::gsbase => {
				ILVal::Word(self.gsbase)
			}
			x86Reg::sp => {
				let val = self.esp;
				ILVal::Short(val as u16)
			}
			x86Reg::bp => {
				let val = self.ebp;
				ILVal::Short(val as u16)
			}
			x86Reg::si => {
				let val = self.esi;
				ILVal::Short(val as u16)
			}
			x86Reg::di => {
				let val = self.edi;
				ILVal::Short(val as u16)
			}
			x86Reg::flags => {
				let val = self.eflags;
				ILVal::Short(val as u16)
			}
			x86Reg::ax => {
				let val = self.eax;
				ILVal::Short(val as u16)
			}
			x86Reg::cx => {
				let val = self.ecx;
				ILVal::Short(val as u16)
			}
			x86Reg::dx => {
				let val = self.edx;
				ILVal::Short(val as u16)
			}
			x86Reg::bx => {
				let val = self.ebx;
				ILVal::Short(val as u16)
			}
			x86Reg::top => {
				ILVal::Short(self.top)
			}
			x86Reg::x87control => {
				ILVal::Short(self.x87control)
			}
			x86Reg::x87status => {
				ILVal::Short(self.x87status)
			}
			x86Reg::x87tag => {
				ILVal::Short(self.x87tag)
			}
			x86Reg::x87push => {
				ILVal::Word(self.x87push)
			}
			x86Reg::x87pop => {
				ILVal::Word(self.x87pop)
			}
			x86Reg::x87pop2 => {
				ILVal::Word(self.x87pop2)
			}
			x86Reg::x87opcode => {
				ILVal::Short(self.x87opcode)
			}
			x86Reg::x87lastcs => {
				ILVal::Short(self.x87lastcs)
			}
			x86Reg::x87lastip => {
				ILVal::Word(self.x87lastip)
			}
			x86Reg::x87lastds => {
				ILVal::Short(self.x87lastds)
			}
			x86Reg::x87lastdp => {
				ILVal::Word(self.x87lastdp)
			}
			x86Reg::eip => {
				ILVal::Word(self.eip)
			}
			x86Reg::esp => {
				ILVal::Word(self.esp)
			}
			x86Reg::ebp => {
				ILVal::Word(self.ebp)
			}
			x86Reg::esi => {
				ILVal::Word(self.esi)
			}
			x86Reg::edi => {
				ILVal::Word(self.edi)
			}
			x86Reg::eflags => {
				ILVal::Word(self.eflags)
			}
			x86Reg::eax => {
				ILVal::Word(self.eax)
			}
			x86Reg::ecx => {
				ILVal::Word(self.ecx)
			}
			x86Reg::edx => {
				ILVal::Word(self.edx)
			}
			x86Reg::ebx => {
				ILVal::Word(self.ebx)
			}
			x86Reg::tsc => {
				ILVal::Word(self.tsc)
			}
			x86Reg::tscaux => {
				ILVal::Word(self.tscaux)
			}
			x86Reg::tr => {
				ILVal::Word(self.tr)
			}
			x86Reg::cr0 => {
				ILVal::Word(self.cr0)
			}
			x86Reg::cr1 => {
				ILVal::Word(self.cr1)
			}
			x86Reg::cr2 => {
				ILVal::Word(self.cr2)
			}
			x86Reg::cr3 => {
				ILVal::Word(self.cr3)
			}
			x86Reg::cr4 => {
				ILVal::Word(self.cr4)
			}
			x86Reg::cr5 => {
				ILVal::Word(self.cr5)
			}
			x86Reg::cr6 => {
				ILVal::Word(self.cr6)
			}
			x86Reg::cr7 => {
				ILVal::Word(self.cr7)
			}
			x86Reg::cr8 => {
				ILVal::Word(self.cr8)
			}
			x86Reg::cr9 => {
				ILVal::Word(self.cr9)
			}
			x86Reg::cr10 => {
				ILVal::Word(self.cr10)
			}
			x86Reg::cr11 => {
				ILVal::Word(self.cr11)
			}
			x86Reg::cr12 => {
				ILVal::Word(self.cr12)
			}
			x86Reg::cr13 => {
				ILVal::Word(self.cr13)
			}
			x86Reg::cr14 => {
				ILVal::Word(self.cr14)
			}
			x86Reg::cr15 => {
				ILVal::Word(self.cr15)
			}
			x86Reg::dr0 => {
				ILVal::Word(self.dr0)
			}
			x86Reg::dr1 => {
				ILVal::Word(self.dr1)
			}
			x86Reg::dr2 => {
				ILVal::Word(self.dr2)
			}
			x86Reg::dr3 => {
				ILVal::Word(self.dr3)
			}
			x86Reg::dr4 => {
				ILVal::Word(self.dr4)
			}
			x86Reg::dr5 => {
				ILVal::Word(self.dr5)
			}
			x86Reg::dr6 => {
				ILVal::Word(self.dr6)
			}
			x86Reg::dr7 => {
				ILVal::Word(self.dr7)
			}
			x86Reg::mxcsr => {
				ILVal::Word(self.mxcsr)
			}
			x86Reg::gdtr => {
				ILVal::Big(Big::from(self.gdtr))
			}
			x86Reg::ldtr => {
				ILVal::Big(Big::from(self.ldtr))
			}
			x86Reg::idtr => {
				ILVal::Big(Big::from(self.idtr))
			}
			x86Reg::mm0 => {
				let val = &self.st0;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::mm1 => {
				let val = &self.st1;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::mm2 => {
				let val = &self.st2;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::mm3 => {
				let val = &self.st3;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::mm4 => {
				let val = &self.st4;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::mm5 => {
				let val = &self.st5;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::mm6 => {
				let val = &self.st6;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::mm7 => {
				let val = &self.st7;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86Reg::xcr0 => {
				ILVal::Quad(self.xcr0)
			}
			x86Reg::rflags => {
				ILVal::Quad(self.rflags)
			}
			x86Reg::msrs => {
				ILVal::Quad(self.msrs)
			}
			x86Reg::st0 => {
				ILVal::Big(Big::from(self.st0))
			}
			x86Reg::st1 => {
				ILVal::Big(Big::from(self.st1))
			}
			x86Reg::st2 => {
				ILVal::Big(Big::from(self.st2))
			}
			x86Reg::st3 => {
				ILVal::Big(Big::from(self.st3))
			}
			x86Reg::st4 => {
				ILVal::Big(Big::from(self.st4))
			}
			x86Reg::st5 => {
				ILVal::Big(Big::from(self.st5))
			}
			x86Reg::st6 => {
				ILVal::Big(Big::from(self.st6))
			}
			x86Reg::st7 => {
				ILVal::Big(Big::from(self.st7))
			}
			x86Reg::x87_r0 => {
				ILVal::Big(Big::from(self.x87_r0))
			}
			x86Reg::x87_r1 => {
				ILVal::Big(Big::from(self.x87_r1))
			}
			x86Reg::x87_r2 => {
				ILVal::Big(Big::from(self.x87_r2))
			}
			x86Reg::x87_r3 => {
				ILVal::Big(Big::from(self.x87_r3))
			}
			x86Reg::x87_r4 => {
				ILVal::Big(Big::from(self.x87_r4))
			}
			x86Reg::x87_r5 => {
				ILVal::Big(Big::from(self.x87_r5))
			}
			x86Reg::x87_r6 => {
				ILVal::Big(Big::from(self.x87_r6))
			}
			x86Reg::x87_r7 => {
				ILVal::Big(Big::from(self.x87_r7))
			}
			x86Reg::xmm0 => {
				ILVal::Big(Big::from(self.xmm0))
			}
			x86Reg::xmm1 => {
				ILVal::Big(Big::from(self.xmm1))
			}
			x86Reg::xmm2 => {
				ILVal::Big(Big::from(self.xmm2))
			}
			x86Reg::xmm3 => {
				ILVal::Big(Big::from(self.xmm3))
			}
			x86Reg::xmm4 => {
				ILVal::Big(Big::from(self.xmm4))
			}
			x86Reg::xmm5 => {
				ILVal::Big(Big::from(self.xmm5))
			}
			x86Reg::xmm6 => {
				ILVal::Big(Big::from(self.xmm6))
			}
			x86Reg::xmm7 => {
				ILVal::Big(Big::from(self.xmm7))
			}
			x86Reg::bnd0 => {
				ILVal::Big(Big::from(self.bnd0))
			}
			x86Reg::bnd1 => {
				ILVal::Big(Big::from(self.bnd1))
			}
			x86Reg::bnd2 => {
				ILVal::Big(Big::from(self.bnd2))
			}
			x86Reg::bnd3 => {
				ILVal::Big(Big::from(self.bnd3))
			}
		}
	}

	fn write(&mut self, id: Self::RegID, val: &ILVal) {
		match id {
			x86Reg::ah => {
				let val = val.get_byte();
				let val = (val as u32) << (8);
				self.eax &= !65280;
				self.eax |= val;
			}
			x86Reg::ch => {
				let val = val.get_byte();
				let val = (val as u32) << (8);
				self.ecx &= !65280;
				self.ecx |= val;
			}
			x86Reg::dh => {
				let val = val.get_byte();
				let val = (val as u32) << (8);
				self.edx &= !65280;
				self.edx |= val;
			}
			x86Reg::bh => {
				let val = val.get_byte();
				let val = (val as u32) << (8);
				self.ebx &= !65280;
				self.ebx |= val;
			}
			x86Reg::al => {
				let val = val.get_byte();
				let val = (val as u32) << (0);
				self.eax &= !255;
				self.eax |= val;
			}
			x86Reg::cl => {
				let val = val.get_byte();
				let val = (val as u32) << (0);
				self.ecx &= !255;
				self.ecx |= val;
			}
			x86Reg::dl => {
				let val = val.get_byte();
				let val = (val as u32) << (0);
				self.edx &= !255;
				self.edx |= val;
			}
			x86Reg::bl => {
				let val = val.get_byte();
				let val = (val as u32) << (0);
				self.ebx &= !255;
				self.ebx |= val;
			}
			x86Reg::ip => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.eip &= !65535;
				self.eip |= val;
			}
			x86Reg::cs => {
				self.cs = val.get_short();
			}
			x86Reg::ds => {
				self.ds = val.get_short();
			}
			x86Reg::es => {
				self.es = val.get_short();
			}
			x86Reg::ss => {
				self.ss = val.get_short();
			}
			x86Reg::fs => {
				self.fs = val.get_short();
			}
			x86Reg::gs => {
				self.gs = val.get_short();
			}
			x86Reg::fsbase => {
				self.fsbase = val.get_word();
			}
			x86Reg::gsbase => {
				self.gsbase = val.get_word();
			}
			x86Reg::sp => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.esp &= !65535;
				self.esp |= val;
			}
			x86Reg::bp => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.ebp &= !65535;
				self.ebp |= val;
			}
			x86Reg::si => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.esi &= !65535;
				self.esi |= val;
			}
			x86Reg::di => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.edi &= !65535;
				self.edi |= val;
			}
			x86Reg::flags => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.eflags &= !65535;
				self.eflags |= val;
			}
			x86Reg::ax => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.eax &= !65535;
				self.eax |= val;
			}
			x86Reg::cx => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.ecx &= !65535;
				self.ecx |= val;
			}
			x86Reg::dx => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.edx &= !65535;
				self.edx |= val;
			}
			x86Reg::bx => {
				let val = val.get_short();
				let val = (val as u32) << (0);
				self.ebx &= !65535;
				self.ebx |= val;
			}
			x86Reg::top => {
				self.top = val.get_short();
			}
			x86Reg::x87control => {
				self.x87control = val.get_short();
			}
			x86Reg::x87status => {
				self.x87status = val.get_short();
			}
			x86Reg::x87tag => {
				self.x87tag = val.get_short();
			}
			x86Reg::x87push => {
				self.x87push = val.get_word();
			}
			x86Reg::x87pop => {
				self.x87pop = val.get_word();
			}
			x86Reg::x87pop2 => {
				self.x87pop2 = val.get_word();
			}
			x86Reg::x87opcode => {
				self.x87opcode = val.get_short();
			}
			x86Reg::x87lastcs => {
				self.x87lastcs = val.get_short();
			}
			x86Reg::x87lastip => {
				self.x87lastip = val.get_word();
			}
			x86Reg::x87lastds => {
				self.x87lastds = val.get_short();
			}
			x86Reg::x87lastdp => {
				self.x87lastdp = val.get_word();
			}
			x86Reg::eip => {
				self.eip = val.get_word();
			}
			x86Reg::esp => {
				self.esp = val.get_word();
			}
			x86Reg::ebp => {
				self.ebp = val.get_word();
			}
			x86Reg::esi => {
				self.esi = val.get_word();
			}
			x86Reg::edi => {
				self.edi = val.get_word();
			}
			x86Reg::eflags => {
				self.eflags = val.get_word();
			}
			x86Reg::eax => {
				self.eax = val.get_word();
			}
			x86Reg::ecx => {
				self.ecx = val.get_word();
			}
			x86Reg::edx => {
				self.edx = val.get_word();
			}
			x86Reg::ebx => {
				self.ebx = val.get_word();
			}
			x86Reg::tsc => {
				self.tsc = val.get_word();
			}
			x86Reg::tscaux => {
				self.tscaux = val.get_word();
			}
			x86Reg::tr => {
				self.tr = val.get_word();
			}
			x86Reg::cr0 => {
				self.cr0 = val.get_word();
			}
			x86Reg::cr1 => {
				self.cr1 = val.get_word();
			}
			x86Reg::cr2 => {
				self.cr2 = val.get_word();
			}
			x86Reg::cr3 => {
				self.cr3 = val.get_word();
			}
			x86Reg::cr4 => {
				self.cr4 = val.get_word();
			}
			x86Reg::cr5 => {
				self.cr5 = val.get_word();
			}
			x86Reg::cr6 => {
				self.cr6 = val.get_word();
			}
			x86Reg::cr7 => {
				self.cr7 = val.get_word();
			}
			x86Reg::cr8 => {
				self.cr8 = val.get_word();
			}
			x86Reg::cr9 => {
				self.cr9 = val.get_word();
			}
			x86Reg::cr10 => {
				self.cr10 = val.get_word();
			}
			x86Reg::cr11 => {
				self.cr11 = val.get_word();
			}
			x86Reg::cr12 => {
				self.cr12 = val.get_word();
			}
			x86Reg::cr13 => {
				self.cr13 = val.get_word();
			}
			x86Reg::cr14 => {
				self.cr14 = val.get_word();
			}
			x86Reg::cr15 => {
				self.cr15 = val.get_word();
			}
			x86Reg::dr0 => {
				self.dr0 = val.get_word();
			}
			x86Reg::dr1 => {
				self.dr1 = val.get_word();
			}
			x86Reg::dr2 => {
				self.dr2 = val.get_word();
			}
			x86Reg::dr3 => {
				self.dr3 = val.get_word();
			}
			x86Reg::dr4 => {
				self.dr4 = val.get_word();
			}
			x86Reg::dr5 => {
				self.dr5 = val.get_word();
			}
			x86Reg::dr6 => {
				self.dr6 = val.get_word();
			}
			x86Reg::dr7 => {
				self.dr7 = val.get_word();
			}
			x86Reg::mxcsr => {
				self.mxcsr = val.get_word();
			}
			x86Reg::gdtr => {
				let big = val.get_big();
				let arr: [u8; 6] = big.as_ref().try_into().expect("Value wrong size for gdtr");
				self.gdtr = arr;
			}
			x86Reg::ldtr => {
				let big = val.get_big();
				let arr: [u8; 6] = big.as_ref().try_into().expect("Value wrong size for ldtr");
				self.ldtr = arr;
			}
			x86Reg::idtr => {
				let big = val.get_big();
				let arr: [u8; 6] = big.as_ref().try_into().expect("Value wrong size for idtr");
				self.idtr = arr;
			}
			x86Reg::mm0 => {
				let val = val.get_quad().to_le_bytes();
				self.st0[0] = val[0];
				self.st0[1] = val[1];
				self.st0[2] = val[2];
				self.st0[3] = val[3];
				self.st0[4] = val[4];
				self.st0[5] = val[5];
				self.st0[6] = val[6];
				self.st0[7] = val[7];
			}
			x86Reg::mm1 => {
				let val = val.get_quad().to_le_bytes();
				self.st1[0] = val[0];
				self.st1[1] = val[1];
				self.st1[2] = val[2];
				self.st1[3] = val[3];
				self.st1[4] = val[4];
				self.st1[5] = val[5];
				self.st1[6] = val[6];
				self.st1[7] = val[7];
			}
			x86Reg::mm2 => {
				let val = val.get_quad().to_le_bytes();
				self.st2[0] = val[0];
				self.st2[1] = val[1];
				self.st2[2] = val[2];
				self.st2[3] = val[3];
				self.st2[4] = val[4];
				self.st2[5] = val[5];
				self.st2[6] = val[6];
				self.st2[7] = val[7];
			}
			x86Reg::mm3 => {
				let val = val.get_quad().to_le_bytes();
				self.st3[0] = val[0];
				self.st3[1] = val[1];
				self.st3[2] = val[2];
				self.st3[3] = val[3];
				self.st3[4] = val[4];
				self.st3[5] = val[5];
				self.st3[6] = val[6];
				self.st3[7] = val[7];
			}
			x86Reg::mm4 => {
				let val = val.get_quad().to_le_bytes();
				self.st4[0] = val[0];
				self.st4[1] = val[1];
				self.st4[2] = val[2];
				self.st4[3] = val[3];
				self.st4[4] = val[4];
				self.st4[5] = val[5];
				self.st4[6] = val[6];
				self.st4[7] = val[7];
			}
			x86Reg::mm5 => {
				let val = val.get_quad().to_le_bytes();
				self.st5[0] = val[0];
				self.st5[1] = val[1];
				self.st5[2] = val[2];
				self.st5[3] = val[3];
				self.st5[4] = val[4];
				self.st5[5] = val[5];
				self.st5[6] = val[6];
				self.st5[7] = val[7];
			}
			x86Reg::mm6 => {
				let val = val.get_quad().to_le_bytes();
				self.st6[0] = val[0];
				self.st6[1] = val[1];
				self.st6[2] = val[2];
				self.st6[3] = val[3];
				self.st6[4] = val[4];
				self.st6[5] = val[5];
				self.st6[6] = val[6];
				self.st6[7] = val[7];
			}
			x86Reg::mm7 => {
				let val = val.get_quad().to_le_bytes();
				self.st7[0] = val[0];
				self.st7[1] = val[1];
				self.st7[2] = val[2];
				self.st7[3] = val[3];
				self.st7[4] = val[4];
				self.st7[5] = val[5];
				self.st7[6] = val[6];
				self.st7[7] = val[7];
			}
			x86Reg::xcr0 => {
				self.xcr0 = val.get_quad();
			}
			x86Reg::rflags => {
				self.rflags = val.get_quad();
			}
			x86Reg::msrs => {
				self.msrs = val.get_quad();
			}
			x86Reg::st0 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st0");
				self.st0 = arr;
			}
			x86Reg::st1 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st1");
				self.st1 = arr;
			}
			x86Reg::st2 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st2");
				self.st2 = arr;
			}
			x86Reg::st3 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st3");
				self.st3 = arr;
			}
			x86Reg::st4 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st4");
				self.st4 = arr;
			}
			x86Reg::st5 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st5");
				self.st5 = arr;
			}
			x86Reg::st6 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st6");
				self.st6 = arr;
			}
			x86Reg::st7 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st7");
				self.st7 = arr;
			}
			x86Reg::x87_r0 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r0");
				self.x87_r0 = arr;
			}
			x86Reg::x87_r1 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r1");
				self.x87_r1 = arr;
			}
			x86Reg::x87_r2 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r2");
				self.x87_r2 = arr;
			}
			x86Reg::x87_r3 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r3");
				self.x87_r3 = arr;
			}
			x86Reg::x87_r4 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r4");
				self.x87_r4 = arr;
			}
			x86Reg::x87_r5 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r5");
				self.x87_r5 = arr;
			}
			x86Reg::x87_r6 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r6");
				self.x87_r6 = arr;
			}
			x86Reg::x87_r7 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r7");
				self.x87_r7 = arr;
			}
			x86Reg::xmm0 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm0");
				self.xmm0 = arr;
			}
			x86Reg::xmm1 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm1");
				self.xmm1 = arr;
			}
			x86Reg::xmm2 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm2");
				self.xmm2 = arr;
			}
			x86Reg::xmm3 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm3");
				self.xmm3 = arr;
			}
			x86Reg::xmm4 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm4");
				self.xmm4 = arr;
			}
			x86Reg::xmm5 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm5");
				self.xmm5 = arr;
			}
			x86Reg::xmm6 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm6");
				self.xmm6 = arr;
			}
			x86Reg::xmm7 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for xmm7");
				self.xmm7 = arr;
			}
			x86Reg::bnd0 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd0");
				self.bnd0 = arr;
			}
			x86Reg::bnd1 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd1");
				self.bnd1 = arr;
			}
			x86Reg::bnd2 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd2");
				self.bnd2 = arr;
			}
			x86Reg::bnd3 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd3");
				self.bnd3 = arr;
			}
		}
	}
}

