//! Register file definition for x86_64.
//!
//! This file was generated by `gen_reg_file.py`

#![allow(non_camel_case_types)]

use crate::{Register, RegState};
#[allow(unused_imports)]
use val::{Big, ILVal};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum x86_64Reg {
	ah,
	al,
	ax,
	bh,
	bl,
	bnd0,
	bnd1,
	bnd2,
	bnd3,
	bndcfgu,
	bndstatus,
	bp,
	bpl,
	bx,
	ch,
	cl,
	cr0,
	cr1,
	cr10,
	cr11,
	cr12,
	cr13,
	cr14,
	cr15,
	cr2,
	cr3,
	cr4,
	cr5,
	cr6,
	cr7,
	cr8,
	cr9,
	cs,
	cx,
	dh,
	di,
	dil,
	dl,
	dr0,
	dr1,
	dr2,
	dr3,
	dr4,
	dr5,
	dr6,
	dr7,
	ds,
	dx,
	eax,
	ebp,
	ebx,
	ecx,
	edi,
	edx,
	eflags,
	eip,
	es,
	esi,
	esp,
	flags,
	fs,
	fsbase,
	gdtr,
	gs,
	gsbase,
	idtr,
	ip,
	k0,
	k1,
	k2,
	k3,
	k4,
	k5,
	k6,
	k7,
	ldtr,
	mm0,
	mm1,
	mm2,
	mm3,
	mm4,
	mm5,
	mm6,
	mm7,
	msrs,
	mxcsr,
	r10,
	r10b,
	r10d,
	r10w,
	r11,
	r11b,
	r11d,
	r11w,
	r12,
	r12b,
	r12d,
	r12w,
	r13,
	r13b,
	r13d,
	r13w,
	r14,
	r14b,
	r14d,
	r14w,
	r15,
	r15b,
	r15d,
	r15w,
	r8,
	r8b,
	r8d,
	r8w,
	r9,
	r9b,
	r9d,
	r9w,
	rax,
	rbp,
	rbx,
	rcx,
	rdi,
	rdx,
	rflags,
	rip,
	rsi,
	rsp,
	si,
	sil,
	sp,
	spl,
	ss,
	ssp,
	st0,
	st1,
	st2,
	st3,
	st4,
	st5,
	st6,
	st7,
	top,
	tr,
	tsc,
	tscaux,
	x87_r0,
	x87_r1,
	x87_r2,
	x87_r3,
	x87_r4,
	x87_r5,
	x87_r6,
	x87_r7,
	x87control,
	x87lastcs,
	x87lastdp,
	x87lastds,
	x87lastip,
	x87opcode,
	x87pop,
	x87pop2,
	x87push,
	x87status,
	x87tag,
	xcr0,
	xmm0,
	xmm1,
	xmm10,
	xmm11,
	xmm12,
	xmm13,
	xmm14,
	xmm15,
	xmm16,
	xmm17,
	xmm18,
	xmm19,
	xmm2,
	xmm20,
	xmm21,
	xmm22,
	xmm23,
	xmm24,
	xmm25,
	xmm26,
	xmm27,
	xmm28,
	xmm29,
	xmm3,
	xmm30,
	xmm31,
	xmm4,
	xmm5,
	xmm6,
	xmm7,
	xmm8,
	xmm9,
	ymm0,
	ymm1,
	ymm10,
	ymm11,
	ymm12,
	ymm13,
	ymm14,
	ymm15,
	ymm16,
	ymm17,
	ymm18,
	ymm19,
	ymm2,
	ymm20,
	ymm21,
	ymm22,
	ymm23,
	ymm24,
	ymm25,
	ymm26,
	ymm27,
	ymm28,
	ymm29,
	ymm3,
	ymm30,
	ymm31,
	ymm4,
	ymm5,
	ymm6,
	ymm7,
	ymm8,
	ymm9,
	zmm0,
	zmm1,
	zmm10,
	zmm11,
	zmm12,
	zmm13,
	zmm14,
	zmm15,
	zmm16,
	zmm17,
	zmm18,
	zmm19,
	zmm2,
	zmm20,
	zmm21,
	zmm22,
	zmm23,
	zmm24,
	zmm25,
	zmm26,
	zmm27,
	zmm28,
	zmm29,
	zmm3,
	zmm30,
	zmm31,
	zmm4,
	zmm5,
	zmm6,
	zmm7,
	zmm8,
	zmm9,
}

impl TryFrom<u32> for x86_64Reg {
	type Error = u32;

	fn try_from(reg_id: u32) -> Result<Self, u32> {
		match reg_id {
			162 => Ok(Self::ah),
			163 => Ok(Self::ch),
			164 => Ok(Self::dh),
			165 => Ok(Self::bh),
			130 => Ok(Self::al),
			131 => Ok(Self::cl),
			132 => Ok(Self::dl),
			133 => Ok(Self::bl),
			134 => Ok(Self::spl),
			135 => Ok(Self::bpl),
			136 => Ok(Self::sil),
			137 => Ok(Self::dil),
			138 => Ok(Self::r8b),
			139 => Ok(Self::r9b),
			140 => Ok(Self::r10b),
			141 => Ok(Self::r11b),
			142 => Ok(Self::r12b),
			143 => Ok(Self::r13b),
			144 => Ok(Self::r14b),
			145 => Ok(Self::r15b),
			169 => Ok(Self::ip),
			230 => Ok(Self::cs),
			232 => Ok(Self::ds),
			229 => Ok(Self::es),
			231 => Ok(Self::ss),
			233 => Ok(Self::fs),
			234 => Ok(Self::gs),
			198 => Ok(Self::fsbase),
			199 => Ok(Self::gsbase),
			38 => Ok(Self::sp),
			39 => Ok(Self::bp),
			40 => Ok(Self::si),
			41 => Ok(Self::di),
			31 => Ok(Self::flags),
			4104 => Ok(Self::top),
			218 => Ok(Self::x87control),
			219 => Ok(Self::x87status),
			220 => Ok(Self::x87tag),
			221 => Ok(Self::x87push),
			222 => Ok(Self::x87pop),
			223 => Ok(Self::x87pop2),
			224 => Ok(Self::x87opcode),
			225 => Ok(Self::x87lastcs),
			226 => Ok(Self::x87lastip),
			227 => Ok(Self::x87lastds),
			228 => Ok(Self::x87lastdp),
			34 => Ok(Self::ax),
			35 => Ok(Self::cx),
			36 => Ok(Self::dx),
			37 => Ok(Self::bx),
			42 => Ok(Self::r8w),
			43 => Ok(Self::r9w),
			44 => Ok(Self::r10w),
			45 => Ok(Self::r11w),
			46 => Ok(Self::r12w),
			47 => Ok(Self::r13w),
			48 => Ok(Self::r14w),
			49 => Ok(Self::r15w),
			168 => Ok(Self::eip),
			70 => Ok(Self::esp),
			71 => Ok(Self::ebp),
			72 => Ok(Self::esi),
			73 => Ok(Self::edi),
			32 => Ok(Self::eflags),
			66 => Ok(Self::eax),
			67 => Ok(Self::ecx),
			68 => Ok(Self::edx),
			69 => Ok(Self::ebx),
			74 => Ok(Self::r8d),
			75 => Ok(Self::r9d),
			76 => Ok(Self::r10d),
			77 => Ok(Self::r11d),
			78 => Ok(Self::r12d),
			79 => Ok(Self::r13d),
			80 => Ok(Self::r14d),
			81 => Ok(Self::r15d),
			191 => Ok(Self::gdtr),
			192 => Ok(Self::ldtr),
			193 => Ok(Self::idtr),
			194 => Ok(Self::tr),
			195 => Ok(Self::tsc),
			196 => Ok(Self::tscaux),
			178 => Ok(Self::mm0),
			179 => Ok(Self::mm1),
			180 => Ok(Self::mm2),
			181 => Ok(Self::mm3),
			182 => Ok(Self::mm4),
			183 => Ok(Self::mm5),
			184 => Ok(Self::mm6),
			185 => Ok(Self::mm7),
			167 => Ok(Self::rip),
			102 => Ok(Self::rsp),
			103 => Ok(Self::rbp),
			104 => Ok(Self::rsi),
			105 => Ok(Self::rdi),
			33 => Ok(Self::rflags),
			188 => Ok(Self::mxcsr),
			268 => Ok(Self::xcr0),
			186 => Ok(Self::ssp),
			98 => Ok(Self::rax),
			99 => Ok(Self::rcx),
			100 => Ok(Self::rdx),
			101 => Ok(Self::rbx),
			106 => Ok(Self::r8),
			107 => Ok(Self::r9),
			108 => Ok(Self::r10),
			109 => Ok(Self::r11),
			110 => Ok(Self::r12),
			111 => Ok(Self::r13),
			112 => Ok(Self::r14),
			113 => Ok(Self::r15),
			1 => Ok(Self::bndcfgu),
			2 => Ok(Self::bndstatus),
			170 => Ok(Self::k0),
			171 => Ok(Self::k1),
			172 => Ok(Self::k2),
			173 => Ok(Self::k3),
			174 => Ok(Self::k4),
			175 => Ok(Self::k5),
			176 => Ok(Self::k6),
			177 => Ok(Self::k7),
			197 => Ok(Self::msrs),
			7 => Ok(Self::cr0),
			8 => Ok(Self::cr1),
			9 => Ok(Self::cr2),
			10 => Ok(Self::cr3),
			11 => Ok(Self::cr4),
			12 => Ok(Self::cr5),
			13 => Ok(Self::cr6),
			14 => Ok(Self::cr7),
			15 => Ok(Self::cr8),
			16 => Ok(Self::cr9),
			17 => Ok(Self::cr10),
			18 => Ok(Self::cr11),
			19 => Ok(Self::cr12),
			20 => Ok(Self::cr13),
			21 => Ok(Self::cr14),
			22 => Ok(Self::cr15),
			23 => Ok(Self::dr0),
			24 => Ok(Self::dr1),
			25 => Ok(Self::dr2),
			26 => Ok(Self::dr3),
			27 => Ok(Self::dr4),
			28 => Ok(Self::dr5),
			29 => Ok(Self::dr6),
			30 => Ok(Self::dr7),
			260 => Ok(Self::st0),
			261 => Ok(Self::st1),
			262 => Ok(Self::st2),
			263 => Ok(Self::st3),
			264 => Ok(Self::st4),
			265 => Ok(Self::st5),
			266 => Ok(Self::st6),
			267 => Ok(Self::st7),
			4096 => Ok(Self::x87_r0),
			4097 => Ok(Self::x87_r1),
			4098 => Ok(Self::x87_r2),
			4099 => Ok(Self::x87_r3),
			4100 => Ok(Self::x87_r4),
			4101 => Ok(Self::x87_r5),
			4102 => Ok(Self::x87_r6),
			4103 => Ok(Self::x87_r7),
			269 => Ok(Self::xmm0),
			270 => Ok(Self::xmm1),
			271 => Ok(Self::xmm2),
			272 => Ok(Self::xmm3),
			273 => Ok(Self::xmm4),
			274 => Ok(Self::xmm5),
			275 => Ok(Self::xmm6),
			276 => Ok(Self::xmm7),
			277 => Ok(Self::xmm8),
			278 => Ok(Self::xmm9),
			279 => Ok(Self::xmm10),
			280 => Ok(Self::xmm11),
			281 => Ok(Self::xmm12),
			282 => Ok(Self::xmm13),
			283 => Ok(Self::xmm14),
			284 => Ok(Self::xmm15),
			285 => Ok(Self::xmm16),
			286 => Ok(Self::xmm17),
			287 => Ok(Self::xmm18),
			288 => Ok(Self::xmm19),
			289 => Ok(Self::xmm20),
			290 => Ok(Self::xmm21),
			291 => Ok(Self::xmm22),
			292 => Ok(Self::xmm23),
			293 => Ok(Self::xmm24),
			294 => Ok(Self::xmm25),
			295 => Ok(Self::xmm26),
			296 => Ok(Self::xmm27),
			297 => Ok(Self::xmm28),
			298 => Ok(Self::xmm29),
			299 => Ok(Self::xmm30),
			300 => Ok(Self::xmm31),
			3 => Ok(Self::bnd0),
			4 => Ok(Self::bnd1),
			5 => Ok(Self::bnd2),
			6 => Ok(Self::bnd3),
			301 => Ok(Self::ymm0),
			302 => Ok(Self::ymm1),
			303 => Ok(Self::ymm2),
			304 => Ok(Self::ymm3),
			305 => Ok(Self::ymm4),
			306 => Ok(Self::ymm5),
			307 => Ok(Self::ymm6),
			308 => Ok(Self::ymm7),
			309 => Ok(Self::ymm8),
			310 => Ok(Self::ymm9),
			311 => Ok(Self::ymm10),
			312 => Ok(Self::ymm11),
			313 => Ok(Self::ymm12),
			314 => Ok(Self::ymm13),
			315 => Ok(Self::ymm14),
			316 => Ok(Self::ymm15),
			317 => Ok(Self::ymm16),
			318 => Ok(Self::ymm17),
			319 => Ok(Self::ymm18),
			320 => Ok(Self::ymm19),
			321 => Ok(Self::ymm20),
			322 => Ok(Self::ymm21),
			323 => Ok(Self::ymm22),
			324 => Ok(Self::ymm23),
			325 => Ok(Self::ymm24),
			326 => Ok(Self::ymm25),
			327 => Ok(Self::ymm26),
			328 => Ok(Self::ymm27),
			329 => Ok(Self::ymm28),
			330 => Ok(Self::ymm29),
			331 => Ok(Self::ymm30),
			332 => Ok(Self::ymm31),
			333 => Ok(Self::zmm0),
			334 => Ok(Self::zmm1),
			335 => Ok(Self::zmm2),
			336 => Ok(Self::zmm3),
			337 => Ok(Self::zmm4),
			338 => Ok(Self::zmm5),
			339 => Ok(Self::zmm6),
			340 => Ok(Self::zmm7),
			341 => Ok(Self::zmm8),
			342 => Ok(Self::zmm9),
			343 => Ok(Self::zmm10),
			344 => Ok(Self::zmm11),
			345 => Ok(Self::zmm12),
			346 => Ok(Self::zmm13),
			347 => Ok(Self::zmm14),
			348 => Ok(Self::zmm15),
			349 => Ok(Self::zmm16),
			350 => Ok(Self::zmm17),
			351 => Ok(Self::zmm18),
			352 => Ok(Self::zmm19),
			353 => Ok(Self::zmm20),
			354 => Ok(Self::zmm21),
			355 => Ok(Self::zmm22),
			356 => Ok(Self::zmm23),
			357 => Ok(Self::zmm24),
			358 => Ok(Self::zmm25),
			359 => Ok(Self::zmm26),
			360 => Ok(Self::zmm27),
			361 => Ok(Self::zmm28),
			362 => Ok(Self::zmm29),
			363 => Ok(Self::zmm30),
			364 => Ok(Self::zmm31),
			_ => Err(reg_id),
		}
	}
}

impl std::fmt::Display for x86_64Reg {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		write!(f, "{:?}", self)
	}
}

impl Register for x86_64Reg {
	fn size(&self) -> u8 {
		match self {
			Self::ah => 1,
			Self::ch => 1,
			Self::dh => 1,
			Self::bh => 1,
			Self::al => 1,
			Self::cl => 1,
			Self::dl => 1,
			Self::bl => 1,
			Self::spl => 1,
			Self::bpl => 1,
			Self::sil => 1,
			Self::dil => 1,
			Self::r8b => 1,
			Self::r9b => 1,
			Self::r10b => 1,
			Self::r11b => 1,
			Self::r12b => 1,
			Self::r13b => 1,
			Self::r14b => 1,
			Self::r15b => 1,
			Self::ip => 2,
			Self::cs => 2,
			Self::ds => 2,
			Self::es => 2,
			Self::ss => 2,
			Self::fs => 2,
			Self::gs => 2,
			Self::fsbase => 8,
			Self::gsbase => 8,
			Self::sp => 2,
			Self::bp => 2,
			Self::si => 2,
			Self::di => 2,
			Self::flags => 2,
			Self::top => 2,
			Self::x87control => 2,
			Self::x87status => 2,
			Self::x87tag => 2,
			Self::x87push => 8,
			Self::x87pop => 8,
			Self::x87pop2 => 8,
			Self::x87opcode => 2,
			Self::x87lastcs => 2,
			Self::x87lastip => 8,
			Self::x87lastds => 2,
			Self::x87lastdp => 8,
			Self::ax => 2,
			Self::cx => 2,
			Self::dx => 2,
			Self::bx => 2,
			Self::r8w => 2,
			Self::r9w => 2,
			Self::r10w => 2,
			Self::r11w => 2,
			Self::r12w => 2,
			Self::r13w => 2,
			Self::r14w => 2,
			Self::r15w => 2,
			Self::eip => 4,
			Self::esp => 4,
			Self::ebp => 4,
			Self::esi => 4,
			Self::edi => 4,
			Self::eflags => 4,
			Self::eax => 4,
			Self::ecx => 4,
			Self::edx => 4,
			Self::ebx => 4,
			Self::r8d => 4,
			Self::r9d => 4,
			Self::r10d => 4,
			Self::r11d => 4,
			Self::r12d => 4,
			Self::r13d => 4,
			Self::r14d => 4,
			Self::r15d => 4,
			Self::gdtr => 6,
			Self::ldtr => 6,
			Self::idtr => 6,
			Self::tr => 8,
			Self::tsc => 8,
			Self::tscaux => 8,
			Self::mm0 => 8,
			Self::mm1 => 8,
			Self::mm2 => 8,
			Self::mm3 => 8,
			Self::mm4 => 8,
			Self::mm5 => 8,
			Self::mm6 => 8,
			Self::mm7 => 8,
			Self::rip => 8,
			Self::rsp => 8,
			Self::rbp => 8,
			Self::rsi => 8,
			Self::rdi => 8,
			Self::rflags => 8,
			Self::mxcsr => 8,
			Self::xcr0 => 8,
			Self::ssp => 8,
			Self::rax => 8,
			Self::rcx => 8,
			Self::rdx => 8,
			Self::rbx => 8,
			Self::r8 => 8,
			Self::r9 => 8,
			Self::r10 => 8,
			Self::r11 => 8,
			Self::r12 => 8,
			Self::r13 => 8,
			Self::r14 => 8,
			Self::r15 => 8,
			Self::bndcfgu => 8,
			Self::bndstatus => 8,
			Self::k0 => 8,
			Self::k1 => 8,
			Self::k2 => 8,
			Self::k3 => 8,
			Self::k4 => 8,
			Self::k5 => 8,
			Self::k6 => 8,
			Self::k7 => 8,
			Self::msrs => 8,
			Self::cr0 => 8,
			Self::cr1 => 8,
			Self::cr2 => 8,
			Self::cr3 => 8,
			Self::cr4 => 8,
			Self::cr5 => 8,
			Self::cr6 => 8,
			Self::cr7 => 8,
			Self::cr8 => 8,
			Self::cr9 => 8,
			Self::cr10 => 8,
			Self::cr11 => 8,
			Self::cr12 => 8,
			Self::cr13 => 8,
			Self::cr14 => 8,
			Self::cr15 => 8,
			Self::dr0 => 8,
			Self::dr1 => 8,
			Self::dr2 => 8,
			Self::dr3 => 8,
			Self::dr4 => 8,
			Self::dr5 => 8,
			Self::dr6 => 8,
			Self::dr7 => 8,
			Self::st0 => 10,
			Self::st1 => 10,
			Self::st2 => 10,
			Self::st3 => 10,
			Self::st4 => 10,
			Self::st5 => 10,
			Self::st6 => 10,
			Self::st7 => 10,
			Self::x87_r0 => 10,
			Self::x87_r1 => 10,
			Self::x87_r2 => 10,
			Self::x87_r3 => 10,
			Self::x87_r4 => 10,
			Self::x87_r5 => 10,
			Self::x87_r6 => 10,
			Self::x87_r7 => 10,
			Self::xmm0 => 16,
			Self::xmm1 => 16,
			Self::xmm2 => 16,
			Self::xmm3 => 16,
			Self::xmm4 => 16,
			Self::xmm5 => 16,
			Self::xmm6 => 16,
			Self::xmm7 => 16,
			Self::xmm8 => 16,
			Self::xmm9 => 16,
			Self::xmm10 => 16,
			Self::xmm11 => 16,
			Self::xmm12 => 16,
			Self::xmm13 => 16,
			Self::xmm14 => 16,
			Self::xmm15 => 16,
			Self::xmm16 => 16,
			Self::xmm17 => 16,
			Self::xmm18 => 16,
			Self::xmm19 => 16,
			Self::xmm20 => 16,
			Self::xmm21 => 16,
			Self::xmm22 => 16,
			Self::xmm23 => 16,
			Self::xmm24 => 16,
			Self::xmm25 => 16,
			Self::xmm26 => 16,
			Self::xmm27 => 16,
			Self::xmm28 => 16,
			Self::xmm29 => 16,
			Self::xmm30 => 16,
			Self::xmm31 => 16,
			Self::bnd0 => 16,
			Self::bnd1 => 16,
			Self::bnd2 => 16,
			Self::bnd3 => 16,
			Self::ymm0 => 32,
			Self::ymm1 => 32,
			Self::ymm2 => 32,
			Self::ymm3 => 32,
			Self::ymm4 => 32,
			Self::ymm5 => 32,
			Self::ymm6 => 32,
			Self::ymm7 => 32,
			Self::ymm8 => 32,
			Self::ymm9 => 32,
			Self::ymm10 => 32,
			Self::ymm11 => 32,
			Self::ymm12 => 32,
			Self::ymm13 => 32,
			Self::ymm14 => 32,
			Self::ymm15 => 32,
			Self::ymm16 => 32,
			Self::ymm17 => 32,
			Self::ymm18 => 32,
			Self::ymm19 => 32,
			Self::ymm20 => 32,
			Self::ymm21 => 32,
			Self::ymm22 => 32,
			Self::ymm23 => 32,
			Self::ymm24 => 32,
			Self::ymm25 => 32,
			Self::ymm26 => 32,
			Self::ymm27 => 32,
			Self::ymm28 => 32,
			Self::ymm29 => 32,
			Self::ymm30 => 32,
			Self::ymm31 => 32,
			Self::zmm0 => 64,
			Self::zmm1 => 64,
			Self::zmm2 => 64,
			Self::zmm3 => 64,
			Self::zmm4 => 64,
			Self::zmm5 => 64,
			Self::zmm6 => 64,
			Self::zmm7 => 64,
			Self::zmm8 => 64,
			Self::zmm9 => 64,
			Self::zmm10 => 64,
			Self::zmm11 => 64,
			Self::zmm12 => 64,
			Self::zmm13 => 64,
			Self::zmm14 => 64,
			Self::zmm15 => 64,
			Self::zmm16 => 64,
			Self::zmm17 => 64,
			Self::zmm18 => 64,
			Self::zmm19 => 64,
			Self::zmm20 => 64,
			Self::zmm21 => 64,
			Self::zmm22 => 64,
			Self::zmm23 => 64,
			Self::zmm24 => 64,
			Self::zmm25 => 64,
			Self::zmm26 => 64,
			Self::zmm27 => 64,
			Self::zmm28 => 64,
			Self::zmm29 => 64,
			Self::zmm30 => 64,
			Self::zmm31 => 64,
		}
	}
}

#[derive(Clone, Copy, Debug)]
pub struct x86_64RegFile {
	pub bnd0: [u8; 16],
	pub bnd1: [u8; 16],
	pub bnd2: [u8; 16],
	pub bnd3: [u8; 16],
	pub bndcfgu: u64,
	pub bndstatus: u64,
	pub cr0: u64,
	pub cr1: u64,
	pub cr10: u64,
	pub cr11: u64,
	pub cr12: u64,
	pub cr13: u64,
	pub cr14: u64,
	pub cr15: u64,
	pub cr2: u64,
	pub cr3: u64,
	pub cr4: u64,
	pub cr5: u64,
	pub cr6: u64,
	pub cr7: u64,
	pub cr8: u64,
	pub cr9: u64,
	pub cs: u16,
	pub dr0: u64,
	pub dr1: u64,
	pub dr2: u64,
	pub dr3: u64,
	pub dr4: u64,
	pub dr5: u64,
	pub dr6: u64,
	pub dr7: u64,
	pub ds: u16,
	pub es: u16,
	pub fs: u16,
	pub fsbase: u64,
	pub gdtr: [u8; 6],
	pub gs: u16,
	pub gsbase: u64,
	pub idtr: [u8; 6],
	pub k0: u64,
	pub k1: u64,
	pub k2: u64,
	pub k3: u64,
	pub k4: u64,
	pub k5: u64,
	pub k6: u64,
	pub k7: u64,
	pub ldtr: [u8; 6],
	pub msrs: u64,
	pub mxcsr: u64,
	pub r10: u64,
	pub r11: u64,
	pub r12: u64,
	pub r13: u64,
	pub r14: u64,
	pub r15: u64,
	pub r8: u64,
	pub r9: u64,
	pub rax: u64,
	pub rbp: u64,
	pub rbx: u64,
	pub rcx: u64,
	pub rdi: u64,
	pub rdx: u64,
	pub rflags: u64,
	pub rip: u64,
	pub rsi: u64,
	pub rsp: u64,
	pub ss: u16,
	pub ssp: u64,
	pub st0: [u8; 10],
	pub st1: [u8; 10],
	pub st2: [u8; 10],
	pub st3: [u8; 10],
	pub st4: [u8; 10],
	pub st5: [u8; 10],
	pub st6: [u8; 10],
	pub st7: [u8; 10],
	pub top: u16,
	pub tr: u64,
	pub tsc: u64,
	pub tscaux: u64,
	pub x87_r0: [u8; 10],
	pub x87_r1: [u8; 10],
	pub x87_r2: [u8; 10],
	pub x87_r3: [u8; 10],
	pub x87_r4: [u8; 10],
	pub x87_r5: [u8; 10],
	pub x87_r6: [u8; 10],
	pub x87_r7: [u8; 10],
	pub x87control: u16,
	pub x87lastcs: u16,
	pub x87lastdp: u64,
	pub x87lastds: u16,
	pub x87lastip: u64,
	pub x87opcode: u16,
	pub x87pop: u64,
	pub x87pop2: u64,
	pub x87push: u64,
	pub x87status: u16,
	pub x87tag: u16,
	pub xcr0: u64,
	pub zmm0: [u8; 64],
	pub zmm1: [u8; 64],
	pub zmm10: [u8; 64],
	pub zmm11: [u8; 64],
	pub zmm12: [u8; 64],
	pub zmm13: [u8; 64],
	pub zmm14: [u8; 64],
	pub zmm15: [u8; 64],
	pub zmm16: [u8; 64],
	pub zmm17: [u8; 64],
	pub zmm18: [u8; 64],
	pub zmm19: [u8; 64],
	pub zmm2: [u8; 64],
	pub zmm20: [u8; 64],
	pub zmm21: [u8; 64],
	pub zmm22: [u8; 64],
	pub zmm23: [u8; 64],
	pub zmm24: [u8; 64],
	pub zmm25: [u8; 64],
	pub zmm26: [u8; 64],
	pub zmm27: [u8; 64],
	pub zmm28: [u8; 64],
	pub zmm29: [u8; 64],
	pub zmm3: [u8; 64],
	pub zmm30: [u8; 64],
	pub zmm31: [u8; 64],
	pub zmm4: [u8; 64],
	pub zmm5: [u8; 64],
	pub zmm6: [u8; 64],
	pub zmm7: [u8; 64],
	pub zmm8: [u8; 64],
	pub zmm9: [u8; 64],
}

impl Default for x86_64RegFile {
	fn default() -> Self {
		Self {
			bnd0: [0u8; 16],
			bnd1: [0u8; 16],
			bnd2: [0u8; 16],
			bnd3: [0u8; 16],
			bndcfgu: 0,
			bndstatus: 0,
			cr0: 0,
			cr1: 0,
			cr10: 0,
			cr11: 0,
			cr12: 0,
			cr13: 0,
			cr14: 0,
			cr15: 0,
			cr2: 0,
			cr3: 0,
			cr4: 0,
			cr5: 0,
			cr6: 0,
			cr7: 0,
			cr8: 0,
			cr9: 0,
			cs: 0,
			dr0: 0,
			dr1: 0,
			dr2: 0,
			dr3: 0,
			dr4: 0,
			dr5: 0,
			dr6: 0,
			dr7: 0,
			ds: 0,
			es: 0,
			fs: 0,
			fsbase: 0,
			gdtr: [0u8; 6],
			gs: 0,
			gsbase: 0,
			idtr: [0u8; 6],
			k0: 0,
			k1: 0,
			k2: 0,
			k3: 0,
			k4: 0,
			k5: 0,
			k6: 0,
			k7: 0,
			ldtr: [0u8; 6],
			msrs: 0,
			mxcsr: 0,
			r10: 0,
			r11: 0,
			r12: 0,
			r13: 0,
			r14: 0,
			r15: 0,
			r8: 0,
			r9: 0,
			rax: 0,
			rbp: 0,
			rbx: 0,
			rcx: 0,
			rdi: 0,
			rdx: 0,
			rflags: 0,
			rip: 0,
			rsi: 0,
			rsp: 0,
			ss: 0,
			ssp: 0,
			st0: [0u8; 10],
			st1: [0u8; 10],
			st2: [0u8; 10],
			st3: [0u8; 10],
			st4: [0u8; 10],
			st5: [0u8; 10],
			st6: [0u8; 10],
			st7: [0u8; 10],
			top: 0,
			tr: 0,
			tsc: 0,
			tscaux: 0,
			x87_r0: [0u8; 10],
			x87_r1: [0u8; 10],
			x87_r2: [0u8; 10],
			x87_r3: [0u8; 10],
			x87_r4: [0u8; 10],
			x87_r5: [0u8; 10],
			x87_r6: [0u8; 10],
			x87_r7: [0u8; 10],
			x87control: 0,
			x87lastcs: 0,
			x87lastdp: 0,
			x87lastds: 0,
			x87lastip: 0,
			x87opcode: 0,
			x87pop: 0,
			x87pop2: 0,
			x87push: 0,
			x87status: 0,
			x87tag: 0,
			xcr0: 0,
			zmm0: [0u8; 64],
			zmm1: [0u8; 64],
			zmm10: [0u8; 64],
			zmm11: [0u8; 64],
			zmm12: [0u8; 64],
			zmm13: [0u8; 64],
			zmm14: [0u8; 64],
			zmm15: [0u8; 64],
			zmm16: [0u8; 64],
			zmm17: [0u8; 64],
			zmm18: [0u8; 64],
			zmm19: [0u8; 64],
			zmm2: [0u8; 64],
			zmm20: [0u8; 64],
			zmm21: [0u8; 64],
			zmm22: [0u8; 64],
			zmm23: [0u8; 64],
			zmm24: [0u8; 64],
			zmm25: [0u8; 64],
			zmm26: [0u8; 64],
			zmm27: [0u8; 64],
			zmm28: [0u8; 64],
			zmm29: [0u8; 64],
			zmm3: [0u8; 64],
			zmm30: [0u8; 64],
			zmm31: [0u8; 64],
			zmm4: [0u8; 64],
			zmm5: [0u8; 64],
			zmm6: [0u8; 64],
			zmm7: [0u8; 64],
			zmm8: [0u8; 64],
			zmm9: [0u8; 64],
		}
	}
}

impl RegState for x86_64RegFile {
	type RegID = x86_64Reg;

	fn read(&self, id: Self::RegID) -> ILVal {
		match id {
			x86_64Reg::ah => {
				let val = self.rax;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86_64Reg::ch => {
				let val = self.rcx;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86_64Reg::dh => {
				let val = self.rdx;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86_64Reg::bh => {
				let val = self.rbx;
				let val = val >> (8);
				ILVal::Byte(val as u8)
			}
			x86_64Reg::al => {
				let val = self.rax;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::cl => {
				let val = self.rcx;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::dl => {
				let val = self.rdx;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::bl => {
				let val = self.rbx;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::spl => {
				let val = self.rsp;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::bpl => {
				let val = self.rbp;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::sil => {
				let val = self.rsi;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::dil => {
				let val = self.rdi;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r8b => {
				let val = self.r8;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r9b => {
				let val = self.r9;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r10b => {
				let val = self.r10;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r11b => {
				let val = self.r11;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r12b => {
				let val = self.r12;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r13b => {
				let val = self.r13;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r14b => {
				let val = self.r14;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::r15b => {
				let val = self.r15;
				ILVal::Byte(val as u8)
			}
			x86_64Reg::ip => {
				let val = self.rip;
				ILVal::Short(val as u16)
			}
			x86_64Reg::cs => {
				ILVal::Short(self.cs)
			}
			x86_64Reg::ds => {
				ILVal::Short(self.ds)
			}
			x86_64Reg::es => {
				ILVal::Short(self.es)
			}
			x86_64Reg::ss => {
				ILVal::Short(self.ss)
			}
			x86_64Reg::fs => {
				ILVal::Short(self.fs)
			}
			x86_64Reg::gs => {
				ILVal::Short(self.gs)
			}
			x86_64Reg::fsbase => {
				ILVal::Quad(self.fsbase)
			}
			x86_64Reg::gsbase => {
				ILVal::Quad(self.gsbase)
			}
			x86_64Reg::sp => {
				let val = self.rsp;
				ILVal::Short(val as u16)
			}
			x86_64Reg::bp => {
				let val = self.rbp;
				ILVal::Short(val as u16)
			}
			x86_64Reg::si => {
				let val = self.rsi;
				ILVal::Short(val as u16)
			}
			x86_64Reg::di => {
				let val = self.rdi;
				ILVal::Short(val as u16)
			}
			x86_64Reg::flags => {
				let val = self.rflags;
				ILVal::Short(val as u16)
			}
			x86_64Reg::top => {
				ILVal::Short(self.top)
			}
			x86_64Reg::x87control => {
				ILVal::Short(self.x87control)
			}
			x86_64Reg::x87status => {
				ILVal::Short(self.x87status)
			}
			x86_64Reg::x87tag => {
				ILVal::Short(self.x87tag)
			}
			x86_64Reg::x87push => {
				ILVal::Quad(self.x87push)
			}
			x86_64Reg::x87pop => {
				ILVal::Quad(self.x87pop)
			}
			x86_64Reg::x87pop2 => {
				ILVal::Quad(self.x87pop2)
			}
			x86_64Reg::x87opcode => {
				ILVal::Short(self.x87opcode)
			}
			x86_64Reg::x87lastcs => {
				ILVal::Short(self.x87lastcs)
			}
			x86_64Reg::x87lastip => {
				ILVal::Quad(self.x87lastip)
			}
			x86_64Reg::x87lastds => {
				ILVal::Short(self.x87lastds)
			}
			x86_64Reg::x87lastdp => {
				ILVal::Quad(self.x87lastdp)
			}
			x86_64Reg::ax => {
				let val = self.rax;
				ILVal::Short(val as u16)
			}
			x86_64Reg::cx => {
				let val = self.rcx;
				ILVal::Short(val as u16)
			}
			x86_64Reg::dx => {
				let val = self.rdx;
				ILVal::Short(val as u16)
			}
			x86_64Reg::bx => {
				let val = self.rbx;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r8w => {
				let val = self.r8;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r9w => {
				let val = self.r9;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r10w => {
				let val = self.r10;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r11w => {
				let val = self.r11;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r12w => {
				let val = self.r12;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r13w => {
				let val = self.r13;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r14w => {
				let val = self.r14;
				ILVal::Short(val as u16)
			}
			x86_64Reg::r15w => {
				let val = self.r15;
				ILVal::Short(val as u16)
			}
			x86_64Reg::eip => {
				let val = self.rip;
				ILVal::Word(val as u32)
			}
			x86_64Reg::esp => {
				let val = self.rsp;
				ILVal::Word(val as u32)
			}
			x86_64Reg::ebp => {
				let val = self.rbp;
				ILVal::Word(val as u32)
			}
			x86_64Reg::esi => {
				let val = self.rsi;
				ILVal::Word(val as u32)
			}
			x86_64Reg::edi => {
				let val = self.rdi;
				ILVal::Word(val as u32)
			}
			x86_64Reg::eflags => {
				let val = self.rflags;
				ILVal::Word(val as u32)
			}
			x86_64Reg::eax => {
				let val = self.rax;
				ILVal::Word(val as u32)
			}
			x86_64Reg::ecx => {
				let val = self.rcx;
				ILVal::Word(val as u32)
			}
			x86_64Reg::edx => {
				let val = self.rdx;
				ILVal::Word(val as u32)
			}
			x86_64Reg::ebx => {
				let val = self.rbx;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r8d => {
				let val = self.r8;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r9d => {
				let val = self.r9;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r10d => {
				let val = self.r10;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r11d => {
				let val = self.r11;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r12d => {
				let val = self.r12;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r13d => {
				let val = self.r13;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r14d => {
				let val = self.r14;
				ILVal::Word(val as u32)
			}
			x86_64Reg::r15d => {
				let val = self.r15;
				ILVal::Word(val as u32)
			}
			x86_64Reg::gdtr => {
				ILVal::Big(Big::from(self.gdtr))
			}
			x86_64Reg::ldtr => {
				ILVal::Big(Big::from(self.ldtr))
			}
			x86_64Reg::idtr => {
				ILVal::Big(Big::from(self.idtr))
			}
			x86_64Reg::tr => {
				ILVal::Quad(self.tr)
			}
			x86_64Reg::tsc => {
				ILVal::Quad(self.tsc)
			}
			x86_64Reg::tscaux => {
				ILVal::Quad(self.tscaux)
			}
			x86_64Reg::mm0 => {
				let val = &self.st0;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::mm1 => {
				let val = &self.st1;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::mm2 => {
				let val = &self.st2;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::mm3 => {
				let val = &self.st3;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::mm4 => {
				let val = &self.st4;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::mm5 => {
				let val = &self.st5;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::mm6 => {
				let val = &self.st6;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::mm7 => {
				let val = &self.st7;
				ILVal::Quad(u64::from_le_bytes([val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7]]))
			}
			x86_64Reg::rip => {
				ILVal::Quad(self.rip)
			}
			x86_64Reg::rsp => {
				ILVal::Quad(self.rsp)
			}
			x86_64Reg::rbp => {
				ILVal::Quad(self.rbp)
			}
			x86_64Reg::rsi => {
				ILVal::Quad(self.rsi)
			}
			x86_64Reg::rdi => {
				ILVal::Quad(self.rdi)
			}
			x86_64Reg::rflags => {
				ILVal::Quad(self.rflags)
			}
			x86_64Reg::mxcsr => {
				ILVal::Quad(self.mxcsr)
			}
			x86_64Reg::xcr0 => {
				ILVal::Quad(self.xcr0)
			}
			x86_64Reg::ssp => {
				ILVal::Quad(self.ssp)
			}
			x86_64Reg::rax => {
				ILVal::Quad(self.rax)
			}
			x86_64Reg::rcx => {
				ILVal::Quad(self.rcx)
			}
			x86_64Reg::rdx => {
				ILVal::Quad(self.rdx)
			}
			x86_64Reg::rbx => {
				ILVal::Quad(self.rbx)
			}
			x86_64Reg::r8 => {
				ILVal::Quad(self.r8)
			}
			x86_64Reg::r9 => {
				ILVal::Quad(self.r9)
			}
			x86_64Reg::r10 => {
				ILVal::Quad(self.r10)
			}
			x86_64Reg::r11 => {
				ILVal::Quad(self.r11)
			}
			x86_64Reg::r12 => {
				ILVal::Quad(self.r12)
			}
			x86_64Reg::r13 => {
				ILVal::Quad(self.r13)
			}
			x86_64Reg::r14 => {
				ILVal::Quad(self.r14)
			}
			x86_64Reg::r15 => {
				ILVal::Quad(self.r15)
			}
			x86_64Reg::bndcfgu => {
				ILVal::Quad(self.bndcfgu)
			}
			x86_64Reg::bndstatus => {
				ILVal::Quad(self.bndstatus)
			}
			x86_64Reg::k0 => {
				ILVal::Quad(self.k0)
			}
			x86_64Reg::k1 => {
				ILVal::Quad(self.k1)
			}
			x86_64Reg::k2 => {
				ILVal::Quad(self.k2)
			}
			x86_64Reg::k3 => {
				ILVal::Quad(self.k3)
			}
			x86_64Reg::k4 => {
				ILVal::Quad(self.k4)
			}
			x86_64Reg::k5 => {
				ILVal::Quad(self.k5)
			}
			x86_64Reg::k6 => {
				ILVal::Quad(self.k6)
			}
			x86_64Reg::k7 => {
				ILVal::Quad(self.k7)
			}
			x86_64Reg::msrs => {
				ILVal::Quad(self.msrs)
			}
			x86_64Reg::cr0 => {
				ILVal::Quad(self.cr0)
			}
			x86_64Reg::cr1 => {
				ILVal::Quad(self.cr1)
			}
			x86_64Reg::cr2 => {
				ILVal::Quad(self.cr2)
			}
			x86_64Reg::cr3 => {
				ILVal::Quad(self.cr3)
			}
			x86_64Reg::cr4 => {
				ILVal::Quad(self.cr4)
			}
			x86_64Reg::cr5 => {
				ILVal::Quad(self.cr5)
			}
			x86_64Reg::cr6 => {
				ILVal::Quad(self.cr6)
			}
			x86_64Reg::cr7 => {
				ILVal::Quad(self.cr7)
			}
			x86_64Reg::cr8 => {
				ILVal::Quad(self.cr8)
			}
			x86_64Reg::cr9 => {
				ILVal::Quad(self.cr9)
			}
			x86_64Reg::cr10 => {
				ILVal::Quad(self.cr10)
			}
			x86_64Reg::cr11 => {
				ILVal::Quad(self.cr11)
			}
			x86_64Reg::cr12 => {
				ILVal::Quad(self.cr12)
			}
			x86_64Reg::cr13 => {
				ILVal::Quad(self.cr13)
			}
			x86_64Reg::cr14 => {
				ILVal::Quad(self.cr14)
			}
			x86_64Reg::cr15 => {
				ILVal::Quad(self.cr15)
			}
			x86_64Reg::dr0 => {
				ILVal::Quad(self.dr0)
			}
			x86_64Reg::dr1 => {
				ILVal::Quad(self.dr1)
			}
			x86_64Reg::dr2 => {
				ILVal::Quad(self.dr2)
			}
			x86_64Reg::dr3 => {
				ILVal::Quad(self.dr3)
			}
			x86_64Reg::dr4 => {
				ILVal::Quad(self.dr4)
			}
			x86_64Reg::dr5 => {
				ILVal::Quad(self.dr5)
			}
			x86_64Reg::dr6 => {
				ILVal::Quad(self.dr6)
			}
			x86_64Reg::dr7 => {
				ILVal::Quad(self.dr7)
			}
			x86_64Reg::st0 => {
				ILVal::Big(Big::from(self.st0))
			}
			x86_64Reg::st1 => {
				ILVal::Big(Big::from(self.st1))
			}
			x86_64Reg::st2 => {
				ILVal::Big(Big::from(self.st2))
			}
			x86_64Reg::st3 => {
				ILVal::Big(Big::from(self.st3))
			}
			x86_64Reg::st4 => {
				ILVal::Big(Big::from(self.st4))
			}
			x86_64Reg::st5 => {
				ILVal::Big(Big::from(self.st5))
			}
			x86_64Reg::st6 => {
				ILVal::Big(Big::from(self.st6))
			}
			x86_64Reg::st7 => {
				ILVal::Big(Big::from(self.st7))
			}
			x86_64Reg::x87_r0 => {
				ILVal::Big(Big::from(self.x87_r0))
			}
			x86_64Reg::x87_r1 => {
				ILVal::Big(Big::from(self.x87_r1))
			}
			x86_64Reg::x87_r2 => {
				ILVal::Big(Big::from(self.x87_r2))
			}
			x86_64Reg::x87_r3 => {
				ILVal::Big(Big::from(self.x87_r3))
			}
			x86_64Reg::x87_r4 => {
				ILVal::Big(Big::from(self.x87_r4))
			}
			x86_64Reg::x87_r5 => {
				ILVal::Big(Big::from(self.x87_r5))
			}
			x86_64Reg::x87_r6 => {
				ILVal::Big(Big::from(self.x87_r6))
			}
			x86_64Reg::x87_r7 => {
				ILVal::Big(Big::from(self.x87_r7))
			}
			x86_64Reg::xmm0 => {
				let val = &self.zmm0;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm1 => {
				let val = &self.zmm1;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm2 => {
				let val = &self.zmm2;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm3 => {
				let val = &self.zmm3;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm4 => {
				let val = &self.zmm4;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm5 => {
				let val = &self.zmm5;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm6 => {
				let val = &self.zmm6;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm7 => {
				let val = &self.zmm7;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm8 => {
				let val = &self.zmm8;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm9 => {
				let val = &self.zmm9;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm10 => {
				let val = &self.zmm10;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm11 => {
				let val = &self.zmm11;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm12 => {
				let val = &self.zmm12;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm13 => {
				let val = &self.zmm13;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm14 => {
				let val = &self.zmm14;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm15 => {
				let val = &self.zmm15;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm16 => {
				let val = &self.zmm16;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm17 => {
				let val = &self.zmm17;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm18 => {
				let val = &self.zmm18;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm19 => {
				let val = &self.zmm19;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm20 => {
				let val = &self.zmm20;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm21 => {
				let val = &self.zmm21;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm22 => {
				let val = &self.zmm22;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm23 => {
				let val = &self.zmm23;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm24 => {
				let val = &self.zmm24;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm25 => {
				let val = &self.zmm25;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm26 => {
				let val = &self.zmm26;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm27 => {
				let val = &self.zmm27;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm28 => {
				let val = &self.zmm28;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm29 => {
				let val = &self.zmm29;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm30 => {
				let val = &self.zmm30;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::xmm31 => {
				let val = &self.zmm31;
				ILVal::Big(Big::from(&val[0..16]))
			}
			x86_64Reg::bnd0 => {
				ILVal::Big(Big::from(self.bnd0))
			}
			x86_64Reg::bnd1 => {
				ILVal::Big(Big::from(self.bnd1))
			}
			x86_64Reg::bnd2 => {
				ILVal::Big(Big::from(self.bnd2))
			}
			x86_64Reg::bnd3 => {
				ILVal::Big(Big::from(self.bnd3))
			}
			x86_64Reg::ymm0 => {
				let val = &self.zmm0;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm1 => {
				let val = &self.zmm1;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm2 => {
				let val = &self.zmm2;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm3 => {
				let val = &self.zmm3;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm4 => {
				let val = &self.zmm4;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm5 => {
				let val = &self.zmm5;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm6 => {
				let val = &self.zmm6;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm7 => {
				let val = &self.zmm7;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm8 => {
				let val = &self.zmm8;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm9 => {
				let val = &self.zmm9;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm10 => {
				let val = &self.zmm10;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm11 => {
				let val = &self.zmm11;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm12 => {
				let val = &self.zmm12;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm13 => {
				let val = &self.zmm13;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm14 => {
				let val = &self.zmm14;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm15 => {
				let val = &self.zmm15;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm16 => {
				let val = &self.zmm16;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm17 => {
				let val = &self.zmm17;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm18 => {
				let val = &self.zmm18;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm19 => {
				let val = &self.zmm19;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm20 => {
				let val = &self.zmm20;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm21 => {
				let val = &self.zmm21;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm22 => {
				let val = &self.zmm22;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm23 => {
				let val = &self.zmm23;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm24 => {
				let val = &self.zmm24;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm25 => {
				let val = &self.zmm25;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm26 => {
				let val = &self.zmm26;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm27 => {
				let val = &self.zmm27;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm28 => {
				let val = &self.zmm28;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm29 => {
				let val = &self.zmm29;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm30 => {
				let val = &self.zmm30;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::ymm31 => {
				let val = &self.zmm31;
				ILVal::Big(Big::from(&val[0..32]))
			}
			x86_64Reg::zmm0 => {
				ILVal::Big(Big::from(self.zmm0))
			}
			x86_64Reg::zmm1 => {
				ILVal::Big(Big::from(self.zmm1))
			}
			x86_64Reg::zmm2 => {
				ILVal::Big(Big::from(self.zmm2))
			}
			x86_64Reg::zmm3 => {
				ILVal::Big(Big::from(self.zmm3))
			}
			x86_64Reg::zmm4 => {
				ILVal::Big(Big::from(self.zmm4))
			}
			x86_64Reg::zmm5 => {
				ILVal::Big(Big::from(self.zmm5))
			}
			x86_64Reg::zmm6 => {
				ILVal::Big(Big::from(self.zmm6))
			}
			x86_64Reg::zmm7 => {
				ILVal::Big(Big::from(self.zmm7))
			}
			x86_64Reg::zmm8 => {
				ILVal::Big(Big::from(self.zmm8))
			}
			x86_64Reg::zmm9 => {
				ILVal::Big(Big::from(self.zmm9))
			}
			x86_64Reg::zmm10 => {
				ILVal::Big(Big::from(self.zmm10))
			}
			x86_64Reg::zmm11 => {
				ILVal::Big(Big::from(self.zmm11))
			}
			x86_64Reg::zmm12 => {
				ILVal::Big(Big::from(self.zmm12))
			}
			x86_64Reg::zmm13 => {
				ILVal::Big(Big::from(self.zmm13))
			}
			x86_64Reg::zmm14 => {
				ILVal::Big(Big::from(self.zmm14))
			}
			x86_64Reg::zmm15 => {
				ILVal::Big(Big::from(self.zmm15))
			}
			x86_64Reg::zmm16 => {
				ILVal::Big(Big::from(self.zmm16))
			}
			x86_64Reg::zmm17 => {
				ILVal::Big(Big::from(self.zmm17))
			}
			x86_64Reg::zmm18 => {
				ILVal::Big(Big::from(self.zmm18))
			}
			x86_64Reg::zmm19 => {
				ILVal::Big(Big::from(self.zmm19))
			}
			x86_64Reg::zmm20 => {
				ILVal::Big(Big::from(self.zmm20))
			}
			x86_64Reg::zmm21 => {
				ILVal::Big(Big::from(self.zmm21))
			}
			x86_64Reg::zmm22 => {
				ILVal::Big(Big::from(self.zmm22))
			}
			x86_64Reg::zmm23 => {
				ILVal::Big(Big::from(self.zmm23))
			}
			x86_64Reg::zmm24 => {
				ILVal::Big(Big::from(self.zmm24))
			}
			x86_64Reg::zmm25 => {
				ILVal::Big(Big::from(self.zmm25))
			}
			x86_64Reg::zmm26 => {
				ILVal::Big(Big::from(self.zmm26))
			}
			x86_64Reg::zmm27 => {
				ILVal::Big(Big::from(self.zmm27))
			}
			x86_64Reg::zmm28 => {
				ILVal::Big(Big::from(self.zmm28))
			}
			x86_64Reg::zmm29 => {
				ILVal::Big(Big::from(self.zmm29))
			}
			x86_64Reg::zmm30 => {
				ILVal::Big(Big::from(self.zmm30))
			}
			x86_64Reg::zmm31 => {
				ILVal::Big(Big::from(self.zmm31))
			}
		}
	}

	fn write(&mut self, id: Self::RegID, val: &ILVal) {
		match id {
			x86_64Reg::ah => {
				let val = val.get_byte();
				let val = (val as u64) << (8);
				self.rax &= !65280;
				self.rax |= val;
			}
			x86_64Reg::ch => {
				let val = val.get_byte();
				let val = (val as u64) << (8);
				self.rcx &= !65280;
				self.rcx |= val;
			}
			x86_64Reg::dh => {
				let val = val.get_byte();
				let val = (val as u64) << (8);
				self.rdx &= !65280;
				self.rdx |= val;
			}
			x86_64Reg::bh => {
				let val = val.get_byte();
				let val = (val as u64) << (8);
				self.rbx &= !65280;
				self.rbx |= val;
			}
			x86_64Reg::al => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rax &= !255;
				self.rax |= val;
			}
			x86_64Reg::cl => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rcx &= !255;
				self.rcx |= val;
			}
			x86_64Reg::dl => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rdx &= !255;
				self.rdx |= val;
			}
			x86_64Reg::bl => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rbx &= !255;
				self.rbx |= val;
			}
			x86_64Reg::spl => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rsp &= !255;
				self.rsp |= val;
			}
			x86_64Reg::bpl => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rbp &= !255;
				self.rbp |= val;
			}
			x86_64Reg::sil => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rsi &= !255;
				self.rsi |= val;
			}
			x86_64Reg::dil => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.rdi &= !255;
				self.rdi |= val;
			}
			x86_64Reg::r8b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r8 &= !255;
				self.r8 |= val;
			}
			x86_64Reg::r9b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r9 &= !255;
				self.r9 |= val;
			}
			x86_64Reg::r10b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r10 &= !255;
				self.r10 |= val;
			}
			x86_64Reg::r11b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r11 &= !255;
				self.r11 |= val;
			}
			x86_64Reg::r12b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r12 &= !255;
				self.r12 |= val;
			}
			x86_64Reg::r13b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r13 &= !255;
				self.r13 |= val;
			}
			x86_64Reg::r14b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r14 &= !255;
				self.r14 |= val;
			}
			x86_64Reg::r15b => {
				let val = val.get_byte();
				let val = (val as u64) << (0);
				self.r15 &= !255;
				self.r15 |= val;
			}
			x86_64Reg::ip => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rip &= !65535;
				self.rip |= val;
			}
			x86_64Reg::cs => {
				self.cs = val.get_short();
			}
			x86_64Reg::ds => {
				self.ds = val.get_short();
			}
			x86_64Reg::es => {
				self.es = val.get_short();
			}
			x86_64Reg::ss => {
				self.ss = val.get_short();
			}
			x86_64Reg::fs => {
				self.fs = val.get_short();
			}
			x86_64Reg::gs => {
				self.gs = val.get_short();
			}
			x86_64Reg::fsbase => {
				self.fsbase = val.get_quad();
			}
			x86_64Reg::gsbase => {
				self.gsbase = val.get_quad();
			}
			x86_64Reg::sp => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rsp &= !65535;
				self.rsp |= val;
			}
			x86_64Reg::bp => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rbp &= !65535;
				self.rbp |= val;
			}
			x86_64Reg::si => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rsi &= !65535;
				self.rsi |= val;
			}
			x86_64Reg::di => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rdi &= !65535;
				self.rdi |= val;
			}
			x86_64Reg::flags => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rflags &= !65535;
				self.rflags |= val;
			}
			x86_64Reg::top => {
				self.top = val.get_short();
			}
			x86_64Reg::x87control => {
				self.x87control = val.get_short();
			}
			x86_64Reg::x87status => {
				self.x87status = val.get_short();
			}
			x86_64Reg::x87tag => {
				self.x87tag = val.get_short();
			}
			x86_64Reg::x87push => {
				self.x87push = val.get_quad();
			}
			x86_64Reg::x87pop => {
				self.x87pop = val.get_quad();
			}
			x86_64Reg::x87pop2 => {
				self.x87pop2 = val.get_quad();
			}
			x86_64Reg::x87opcode => {
				self.x87opcode = val.get_short();
			}
			x86_64Reg::x87lastcs => {
				self.x87lastcs = val.get_short();
			}
			x86_64Reg::x87lastip => {
				self.x87lastip = val.get_quad();
			}
			x86_64Reg::x87lastds => {
				self.x87lastds = val.get_short();
			}
			x86_64Reg::x87lastdp => {
				self.x87lastdp = val.get_quad();
			}
			x86_64Reg::ax => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rax &= !65535;
				self.rax |= val;
			}
			x86_64Reg::cx => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rcx &= !65535;
				self.rcx |= val;
			}
			x86_64Reg::dx => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rdx &= !65535;
				self.rdx |= val;
			}
			x86_64Reg::bx => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.rbx &= !65535;
				self.rbx |= val;
			}
			x86_64Reg::r8w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r8 &= !65535;
				self.r8 |= val;
			}
			x86_64Reg::r9w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r9 &= !65535;
				self.r9 |= val;
			}
			x86_64Reg::r10w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r10 &= !65535;
				self.r10 |= val;
			}
			x86_64Reg::r11w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r11 &= !65535;
				self.r11 |= val;
			}
			x86_64Reg::r12w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r12 &= !65535;
				self.r12 |= val;
			}
			x86_64Reg::r13w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r13 &= !65535;
				self.r13 |= val;
			}
			x86_64Reg::r14w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r14 &= !65535;
				self.r14 |= val;
			}
			x86_64Reg::r15w => {
				let val = val.get_short();
				let val = (val as u64) << (0);
				self.r15 &= !65535;
				self.r15 |= val;
			}
			x86_64Reg::eip => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rip &= !4294967295;
				self.rip |= val;
			}
			x86_64Reg::esp => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rsp &= !4294967295;
				self.rsp |= val;
			}
			x86_64Reg::ebp => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rbp &= !4294967295;
				self.rbp |= val;
			}
			x86_64Reg::esi => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rsi &= !4294967295;
				self.rsi |= val;
			}
			x86_64Reg::edi => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rdi &= !4294967295;
				self.rdi |= val;
			}
			x86_64Reg::eflags => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rflags &= !4294967295;
				self.rflags |= val;
			}
			x86_64Reg::eax => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rax &= !4294967295;
				self.rax |= val;
			}
			x86_64Reg::ecx => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rcx &= !4294967295;
				self.rcx |= val;
			}
			x86_64Reg::edx => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rdx &= !4294967295;
				self.rdx |= val;
			}
			x86_64Reg::ebx => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.rbx &= !4294967295;
				self.rbx |= val;
			}
			x86_64Reg::r8d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r8 &= !4294967295;
				self.r8 |= val;
			}
			x86_64Reg::r9d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r9 &= !4294967295;
				self.r9 |= val;
			}
			x86_64Reg::r10d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r10 &= !4294967295;
				self.r10 |= val;
			}
			x86_64Reg::r11d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r11 &= !4294967295;
				self.r11 |= val;
			}
			x86_64Reg::r12d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r12 &= !4294967295;
				self.r12 |= val;
			}
			x86_64Reg::r13d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r13 &= !4294967295;
				self.r13 |= val;
			}
			x86_64Reg::r14d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r14 &= !4294967295;
				self.r14 |= val;
			}
			x86_64Reg::r15d => {
				let val = val.get_word();
				let val = (val as u64) << (0);
				self.r15 &= !4294967295;
				self.r15 |= val;
			}
			x86_64Reg::gdtr => {
				let big = val.get_big();
				let arr: [u8; 6] = big.as_ref().try_into().expect("Value wrong size for gdtr");
				self.gdtr = arr;
			}
			x86_64Reg::ldtr => {
				let big = val.get_big();
				let arr: [u8; 6] = big.as_ref().try_into().expect("Value wrong size for ldtr");
				self.ldtr = arr;
			}
			x86_64Reg::idtr => {
				let big = val.get_big();
				let arr: [u8; 6] = big.as_ref().try_into().expect("Value wrong size for idtr");
				self.idtr = arr;
			}
			x86_64Reg::tr => {
				self.tr = val.get_quad();
			}
			x86_64Reg::tsc => {
				self.tsc = val.get_quad();
			}
			x86_64Reg::tscaux => {
				self.tscaux = val.get_quad();
			}
			x86_64Reg::mm0 => {
				let val = val.get_quad().to_le_bytes();
				self.st0[0] = val[0];
				self.st0[1] = val[1];
				self.st0[2] = val[2];
				self.st0[3] = val[3];
				self.st0[4] = val[4];
				self.st0[5] = val[5];
				self.st0[6] = val[6];
				self.st0[7] = val[7];
			}
			x86_64Reg::mm1 => {
				let val = val.get_quad().to_le_bytes();
				self.st1[0] = val[0];
				self.st1[1] = val[1];
				self.st1[2] = val[2];
				self.st1[3] = val[3];
				self.st1[4] = val[4];
				self.st1[5] = val[5];
				self.st1[6] = val[6];
				self.st1[7] = val[7];
			}
			x86_64Reg::mm2 => {
				let val = val.get_quad().to_le_bytes();
				self.st2[0] = val[0];
				self.st2[1] = val[1];
				self.st2[2] = val[2];
				self.st2[3] = val[3];
				self.st2[4] = val[4];
				self.st2[5] = val[5];
				self.st2[6] = val[6];
				self.st2[7] = val[7];
			}
			x86_64Reg::mm3 => {
				let val = val.get_quad().to_le_bytes();
				self.st3[0] = val[0];
				self.st3[1] = val[1];
				self.st3[2] = val[2];
				self.st3[3] = val[3];
				self.st3[4] = val[4];
				self.st3[5] = val[5];
				self.st3[6] = val[6];
				self.st3[7] = val[7];
			}
			x86_64Reg::mm4 => {
				let val = val.get_quad().to_le_bytes();
				self.st4[0] = val[0];
				self.st4[1] = val[1];
				self.st4[2] = val[2];
				self.st4[3] = val[3];
				self.st4[4] = val[4];
				self.st4[5] = val[5];
				self.st4[6] = val[6];
				self.st4[7] = val[7];
			}
			x86_64Reg::mm5 => {
				let val = val.get_quad().to_le_bytes();
				self.st5[0] = val[0];
				self.st5[1] = val[1];
				self.st5[2] = val[2];
				self.st5[3] = val[3];
				self.st5[4] = val[4];
				self.st5[5] = val[5];
				self.st5[6] = val[6];
				self.st5[7] = val[7];
			}
			x86_64Reg::mm6 => {
				let val = val.get_quad().to_le_bytes();
				self.st6[0] = val[0];
				self.st6[1] = val[1];
				self.st6[2] = val[2];
				self.st6[3] = val[3];
				self.st6[4] = val[4];
				self.st6[5] = val[5];
				self.st6[6] = val[6];
				self.st6[7] = val[7];
			}
			x86_64Reg::mm7 => {
				let val = val.get_quad().to_le_bytes();
				self.st7[0] = val[0];
				self.st7[1] = val[1];
				self.st7[2] = val[2];
				self.st7[3] = val[3];
				self.st7[4] = val[4];
				self.st7[5] = val[5];
				self.st7[6] = val[6];
				self.st7[7] = val[7];
			}
			x86_64Reg::rip => {
				self.rip = val.get_quad();
			}
			x86_64Reg::rsp => {
				self.rsp = val.get_quad();
			}
			x86_64Reg::rbp => {
				self.rbp = val.get_quad();
			}
			x86_64Reg::rsi => {
				self.rsi = val.get_quad();
			}
			x86_64Reg::rdi => {
				self.rdi = val.get_quad();
			}
			x86_64Reg::rflags => {
				self.rflags = val.get_quad();
			}
			x86_64Reg::mxcsr => {
				self.mxcsr = val.get_quad();
			}
			x86_64Reg::xcr0 => {
				self.xcr0 = val.get_quad();
			}
			x86_64Reg::ssp => {
				self.ssp = val.get_quad();
			}
			x86_64Reg::rax => {
				self.rax = val.get_quad();
			}
			x86_64Reg::rcx => {
				self.rcx = val.get_quad();
			}
			x86_64Reg::rdx => {
				self.rdx = val.get_quad();
			}
			x86_64Reg::rbx => {
				self.rbx = val.get_quad();
			}
			x86_64Reg::r8 => {
				self.r8 = val.get_quad();
			}
			x86_64Reg::r9 => {
				self.r9 = val.get_quad();
			}
			x86_64Reg::r10 => {
				self.r10 = val.get_quad();
			}
			x86_64Reg::r11 => {
				self.r11 = val.get_quad();
			}
			x86_64Reg::r12 => {
				self.r12 = val.get_quad();
			}
			x86_64Reg::r13 => {
				self.r13 = val.get_quad();
			}
			x86_64Reg::r14 => {
				self.r14 = val.get_quad();
			}
			x86_64Reg::r15 => {
				self.r15 = val.get_quad();
			}
			x86_64Reg::bndcfgu => {
				self.bndcfgu = val.get_quad();
			}
			x86_64Reg::bndstatus => {
				self.bndstatus = val.get_quad();
			}
			x86_64Reg::k0 => {
				self.k0 = val.get_quad();
			}
			x86_64Reg::k1 => {
				self.k1 = val.get_quad();
			}
			x86_64Reg::k2 => {
				self.k2 = val.get_quad();
			}
			x86_64Reg::k3 => {
				self.k3 = val.get_quad();
			}
			x86_64Reg::k4 => {
				self.k4 = val.get_quad();
			}
			x86_64Reg::k5 => {
				self.k5 = val.get_quad();
			}
			x86_64Reg::k6 => {
				self.k6 = val.get_quad();
			}
			x86_64Reg::k7 => {
				self.k7 = val.get_quad();
			}
			x86_64Reg::msrs => {
				self.msrs = val.get_quad();
			}
			x86_64Reg::cr0 => {
				self.cr0 = val.get_quad();
			}
			x86_64Reg::cr1 => {
				self.cr1 = val.get_quad();
			}
			x86_64Reg::cr2 => {
				self.cr2 = val.get_quad();
			}
			x86_64Reg::cr3 => {
				self.cr3 = val.get_quad();
			}
			x86_64Reg::cr4 => {
				self.cr4 = val.get_quad();
			}
			x86_64Reg::cr5 => {
				self.cr5 = val.get_quad();
			}
			x86_64Reg::cr6 => {
				self.cr6 = val.get_quad();
			}
			x86_64Reg::cr7 => {
				self.cr7 = val.get_quad();
			}
			x86_64Reg::cr8 => {
				self.cr8 = val.get_quad();
			}
			x86_64Reg::cr9 => {
				self.cr9 = val.get_quad();
			}
			x86_64Reg::cr10 => {
				self.cr10 = val.get_quad();
			}
			x86_64Reg::cr11 => {
				self.cr11 = val.get_quad();
			}
			x86_64Reg::cr12 => {
				self.cr12 = val.get_quad();
			}
			x86_64Reg::cr13 => {
				self.cr13 = val.get_quad();
			}
			x86_64Reg::cr14 => {
				self.cr14 = val.get_quad();
			}
			x86_64Reg::cr15 => {
				self.cr15 = val.get_quad();
			}
			x86_64Reg::dr0 => {
				self.dr0 = val.get_quad();
			}
			x86_64Reg::dr1 => {
				self.dr1 = val.get_quad();
			}
			x86_64Reg::dr2 => {
				self.dr2 = val.get_quad();
			}
			x86_64Reg::dr3 => {
				self.dr3 = val.get_quad();
			}
			x86_64Reg::dr4 => {
				self.dr4 = val.get_quad();
			}
			x86_64Reg::dr5 => {
				self.dr5 = val.get_quad();
			}
			x86_64Reg::dr6 => {
				self.dr6 = val.get_quad();
			}
			x86_64Reg::dr7 => {
				self.dr7 = val.get_quad();
			}
			x86_64Reg::st0 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st0");
				self.st0 = arr;
			}
			x86_64Reg::st1 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st1");
				self.st1 = arr;
			}
			x86_64Reg::st2 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st2");
				self.st2 = arr;
			}
			x86_64Reg::st3 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st3");
				self.st3 = arr;
			}
			x86_64Reg::st4 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st4");
				self.st4 = arr;
			}
			x86_64Reg::st5 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st5");
				self.st5 = arr;
			}
			x86_64Reg::st6 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st6");
				self.st6 = arr;
			}
			x86_64Reg::st7 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for st7");
				self.st7 = arr;
			}
			x86_64Reg::x87_r0 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r0");
				self.x87_r0 = arr;
			}
			x86_64Reg::x87_r1 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r1");
				self.x87_r1 = arr;
			}
			x86_64Reg::x87_r2 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r2");
				self.x87_r2 = arr;
			}
			x86_64Reg::x87_r3 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r3");
				self.x87_r3 = arr;
			}
			x86_64Reg::x87_r4 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r4");
				self.x87_r4 = arr;
			}
			x86_64Reg::x87_r5 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r5");
				self.x87_r5 = arr;
			}
			x86_64Reg::x87_r6 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r6");
				self.x87_r6 = arr;
			}
			x86_64Reg::x87_r7 => {
				let big = val.get_big();
				let arr: [u8; 10] = big.as_ref().try_into().expect("Value wrong size for x87_r7");
				self.x87_r7 = arr;
			}
			x86_64Reg::xmm0 => {
				let val = val.get_big();
				self.zmm0[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm1 => {
				let val = val.get_big();
				self.zmm1[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm2 => {
				let val = val.get_big();
				self.zmm2[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm3 => {
				let val = val.get_big();
				self.zmm3[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm4 => {
				let val = val.get_big();
				self.zmm4[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm5 => {
				let val = val.get_big();
				self.zmm5[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm6 => {
				let val = val.get_big();
				self.zmm6[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm7 => {
				let val = val.get_big();
				self.zmm7[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm8 => {
				let val = val.get_big();
				self.zmm8[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm9 => {
				let val = val.get_big();
				self.zmm9[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm10 => {
				let val = val.get_big();
				self.zmm10[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm11 => {
				let val = val.get_big();
				self.zmm11[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm12 => {
				let val = val.get_big();
				self.zmm12[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm13 => {
				let val = val.get_big();
				self.zmm13[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm14 => {
				let val = val.get_big();
				self.zmm14[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm15 => {
				let val = val.get_big();
				self.zmm15[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm16 => {
				let val = val.get_big();
				self.zmm16[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm17 => {
				let val = val.get_big();
				self.zmm17[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm18 => {
				let val = val.get_big();
				self.zmm18[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm19 => {
				let val = val.get_big();
				self.zmm19[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm20 => {
				let val = val.get_big();
				self.zmm20[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm21 => {
				let val = val.get_big();
				self.zmm21[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm22 => {
				let val = val.get_big();
				self.zmm22[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm23 => {
				let val = val.get_big();
				self.zmm23[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm24 => {
				let val = val.get_big();
				self.zmm24[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm25 => {
				let val = val.get_big();
				self.zmm25[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm26 => {
				let val = val.get_big();
				self.zmm26[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm27 => {
				let val = val.get_big();
				self.zmm27[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm28 => {
				let val = val.get_big();
				self.zmm28[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm29 => {
				let val = val.get_big();
				self.zmm29[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm30 => {
				let val = val.get_big();
				self.zmm30[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::xmm31 => {
				let val = val.get_big();
				self.zmm31[0..][..16].copy_from_slice(val.as_ref());
			}
			x86_64Reg::bnd0 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd0");
				self.bnd0 = arr;
			}
			x86_64Reg::bnd1 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd1");
				self.bnd1 = arr;
			}
			x86_64Reg::bnd2 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd2");
				self.bnd2 = arr;
			}
			x86_64Reg::bnd3 => {
				let big = val.get_big();
				let arr: [u8; 16] = big.as_ref().try_into().expect("Value wrong size for bnd3");
				self.bnd3 = arr;
			}
			x86_64Reg::ymm0 => {
				let val = val.get_big();
				self.zmm0[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm1 => {
				let val = val.get_big();
				self.zmm1[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm2 => {
				let val = val.get_big();
				self.zmm2[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm3 => {
				let val = val.get_big();
				self.zmm3[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm4 => {
				let val = val.get_big();
				self.zmm4[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm5 => {
				let val = val.get_big();
				self.zmm5[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm6 => {
				let val = val.get_big();
				self.zmm6[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm7 => {
				let val = val.get_big();
				self.zmm7[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm8 => {
				let val = val.get_big();
				self.zmm8[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm9 => {
				let val = val.get_big();
				self.zmm9[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm10 => {
				let val = val.get_big();
				self.zmm10[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm11 => {
				let val = val.get_big();
				self.zmm11[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm12 => {
				let val = val.get_big();
				self.zmm12[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm13 => {
				let val = val.get_big();
				self.zmm13[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm14 => {
				let val = val.get_big();
				self.zmm14[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm15 => {
				let val = val.get_big();
				self.zmm15[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm16 => {
				let val = val.get_big();
				self.zmm16[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm17 => {
				let val = val.get_big();
				self.zmm17[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm18 => {
				let val = val.get_big();
				self.zmm18[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm19 => {
				let val = val.get_big();
				self.zmm19[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm20 => {
				let val = val.get_big();
				self.zmm20[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm21 => {
				let val = val.get_big();
				self.zmm21[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm22 => {
				let val = val.get_big();
				self.zmm22[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm23 => {
				let val = val.get_big();
				self.zmm23[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm24 => {
				let val = val.get_big();
				self.zmm24[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm25 => {
				let val = val.get_big();
				self.zmm25[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm26 => {
				let val = val.get_big();
				self.zmm26[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm27 => {
				let val = val.get_big();
				self.zmm27[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm28 => {
				let val = val.get_big();
				self.zmm28[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm29 => {
				let val = val.get_big();
				self.zmm29[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm30 => {
				let val = val.get_big();
				self.zmm30[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::ymm31 => {
				let val = val.get_big();
				self.zmm31[0..][..32].copy_from_slice(val.as_ref());
			}
			x86_64Reg::zmm0 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm0");
				self.zmm0 = arr;
			}
			x86_64Reg::zmm1 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm1");
				self.zmm1 = arr;
			}
			x86_64Reg::zmm2 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm2");
				self.zmm2 = arr;
			}
			x86_64Reg::zmm3 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm3");
				self.zmm3 = arr;
			}
			x86_64Reg::zmm4 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm4");
				self.zmm4 = arr;
			}
			x86_64Reg::zmm5 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm5");
				self.zmm5 = arr;
			}
			x86_64Reg::zmm6 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm6");
				self.zmm6 = arr;
			}
			x86_64Reg::zmm7 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm7");
				self.zmm7 = arr;
			}
			x86_64Reg::zmm8 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm8");
				self.zmm8 = arr;
			}
			x86_64Reg::zmm9 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm9");
				self.zmm9 = arr;
			}
			x86_64Reg::zmm10 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm10");
				self.zmm10 = arr;
			}
			x86_64Reg::zmm11 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm11");
				self.zmm11 = arr;
			}
			x86_64Reg::zmm12 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm12");
				self.zmm12 = arr;
			}
			x86_64Reg::zmm13 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm13");
				self.zmm13 = arr;
			}
			x86_64Reg::zmm14 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm14");
				self.zmm14 = arr;
			}
			x86_64Reg::zmm15 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm15");
				self.zmm15 = arr;
			}
			x86_64Reg::zmm16 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm16");
				self.zmm16 = arr;
			}
			x86_64Reg::zmm17 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm17");
				self.zmm17 = arr;
			}
			x86_64Reg::zmm18 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm18");
				self.zmm18 = arr;
			}
			x86_64Reg::zmm19 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm19");
				self.zmm19 = arr;
			}
			x86_64Reg::zmm20 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm20");
				self.zmm20 = arr;
			}
			x86_64Reg::zmm21 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm21");
				self.zmm21 = arr;
			}
			x86_64Reg::zmm22 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm22");
				self.zmm22 = arr;
			}
			x86_64Reg::zmm23 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm23");
				self.zmm23 = arr;
			}
			x86_64Reg::zmm24 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm24");
				self.zmm24 = arr;
			}
			x86_64Reg::zmm25 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm25");
				self.zmm25 = arr;
			}
			x86_64Reg::zmm26 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm26");
				self.zmm26 = arr;
			}
			x86_64Reg::zmm27 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm27");
				self.zmm27 = arr;
			}
			x86_64Reg::zmm28 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm28");
				self.zmm28 = arr;
			}
			x86_64Reg::zmm29 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm29");
				self.zmm29 = arr;
			}
			x86_64Reg::zmm30 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm30");
				self.zmm30 = arr;
			}
			x86_64Reg::zmm31 => {
				let big = val.get_big();
				let arr: [u8; 64] = big.as_ref().try_into().expect("Value wrong size for zmm31");
				self.zmm31 = arr;
			}
		}
	}
}

