import argparse

import binaryninja as bn


def list_archs(_args):
    archs = bn.Architecture
    for arch in list(archs):
        print(arch)


def gen_reg_enum(arch, file):
    regs = arch.regs
    reg_type = f"{arch}Reg"
    file.write("#[allow(non_camel_case_types)]\n")
    file.write("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n")
    file.write(f"pub enum {reg_type} {{\n")
    for k, _v in regs.items():
        file.write(f"    {k},\n")
    file.write("}\n\n")
    file.write(f"impl TryFrom<u32> for {reg_type} {{\n")
    file.write("\ttype Error = u32;\n\n")
    file.write("\tfn try_from(reg_id: u32) -> Result<Self, u32> {\n")
    file.write("\t\tmatch reg_id {\n")
    for k, v in regs.items():
        reg_id = v.index
        file.write(f"\t\t\t{reg_id} => Ok(Self::{k}),\n")
    file.write("\t\t\t_ => Err(reg_id),\n")
    file.write("\t\t}\n\t}\n}\n\n")
    file.write(f"impl std::fmt::Debug for {reg_type} {{\n")
    file.write(
        "\tfn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n"
    )
    file.write('\t\twrite!(f, "{:?}", self)\n')
    file.write("\t}\n}\n\n")
    file.write(f"impl Register for {reg_type} {{}}\n\n")


def gen_arch(args):
    arch = bn.Architecture[args.arch]
    file = args.outfile
    file.write(f"//! Register file definition for {arch}.\n//!\n")
    file.write("//! This file was generated by `gen_reg_file.py`\n\n")
    file.write("use crate::Register;\n\n")
    gen_reg_enum(arch, file)


def main():
    args = argparse.ArgumentParser(
        description="Generate a register file for an architecture supported by binary ninja"
    )
    subparsers = args.add_subparsers(required=True)

    list = subparsers.add_parser("list", description="List supported architectures")
    list.set_defaults(func=list_archs)

    gen = subparsers.add_parser(
        "gen", description="Generate register file for a specific architecture"
    )
    gen.add_argument(
        "arch", help="Architecture to generate register file for", type=str
    )
    gen.add_argument(
        "outfile", help="File to write source to", type=argparse.FileType("w")
    )
    gen.set_defaults(func=gen_arch)

    args = args.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
